export type Unidad = "G" | "ML" | "UD";

export const categories = [
  { id: "entradas", nombre: "Entradas", tipo: "COMIDA" as const, esInterna: false, orden: 1 },
  { id: "especialidades", nombre: "Especialidades de la Montaña", tipo: "COMIDA" as const, esInterna: false, orden: 2 },
  { id: "cortes", nombre: "Cortes y Carnes", tipo: "COMIDA" as const, esInterna: false, orden: 3 },
  { id: "ensaladas", nombre: "Ensaladas", tipo: "COMIDA" as const, esInterna: false, orden: 4 },
  { id: "caldos", nombre: "Caldos", tipo: "COMIDA" as const, esInterna: false, orden: 5 },
  { id: "picaderas", nombre: "Picaderas", tipo: "COMIDA" as const, esInterna: false, orden: 6 },
  { id: "pastas", nombre: "Pastas", tipo: "COMIDA" as const, esInterna: false, orden: 7 },
  { id: "arroces", nombre: "Arroces", tipo: "COMIDA" as const, esInterna: false, orden: 8 },
  { id: "pescados", nombre: "Pescados y Mariscos", tipo: "COMIDA" as const, esInterna: false, orden: 9 },
  { id: "postres", nombre: "Postres", tipo: "COMIDA" as const, esInterna: false, orden: 10 },
  { id: "guarniciones", nombre: "Guarniciones", tipo: "COMIDA" as const, esInterna: false, orden: 11 },
  { id: "desayunos", nombre: "Desayunos", tipo: "COMIDA" as const, esInterna: false, orden: 12 },
  { id: "jugos", nombre: "Jugos Naturales", tipo: "BEBIDA" as const, esInterna: false, orden: 13 },
  { id: "cafes", nombre: "Cafés y Té", tipo: "BEBIDA" as const, esInterna: false, orden: 14 },
  { id: "cervezas", nombre: "Cervezas", tipo: "BEBIDA" as const, esInterna: false, orden: 15 },
  { id: "cocteles", nombre: "Cócteles", tipo: "BEBIDA" as const, esInterna: false, orden: 16 },
  { id: "refrescos", nombre: "Agua y Refrescos", tipo: "BEBIDA" as const, esInterna: false, orden: 17 },
  { id: "ninos", nombre: "Para Niños", tipo: "BEBIDA" as const, esInterna: false, orden: 18 },
  { id: "vinos", nombre: "Vinos", tipo: "BEBIDA" as const, esInterna: false, orden: 19 },
  { id: "licores", nombre: "Tragos", tipo: "BEBIDA" as const, esInterna: false, orden: 20 },
  { id: "emp-comida", nombre: "Comida Empleados", tipo: "COMIDA" as const, esInterna: true, orden: 90 },
  { id: "emp-bebida", nombre: "Consumo Empleados", tipo: "BEBIDA" as const, esInterna: true, orden: 91 },
  { id: "huespedes", nombre: "Huéspedes", tipo: "COMIDA" as const, esInterna: true, orden: 92 },
  { id: "extras", nombre: "Extras Varios", tipo: "COMIDA" as const, esInterna: true, orden: 93 },
];

type DishSeed = {
  id: string;
  nombre: string;
  categoryId: string;
  precio?: number | null;
  descripcion?: string;
  destacado?: boolean;
  incluyeGuarnicion?: boolean;
};

export const dishes: DishSeed[] = [
  { id: "aros-calamar", nombre: "Aros de Calamar", categoryId: "entradas", precio: 495 },
  { id: "croquetas-pollo", nombre: "Croquetas de Pollo", categoryId: "entradas", precio: 425 },
  { id: "bolitas-queso", nombre: "Bolitas de Queso", categoryId: "entradas", precio: 420 },
  { id: "bruschettas", nombre: "Bruschettas de Tomate y Parmesano", categoryId: "entradas", precio: 395 },
  { id: "cativias", nombre: "Cativías (3 por servicio)", categoryId: "entradas", precio: 365, descripcion: "Masa de yuca rellena de queso" },
  { id: "aceitunas-rellenas", nombre: "Aceitunas Rellenas", categoryId: "entradas", precio: 300 },
  { id: "carpaccio-salmon", nombre: "Carpaccio de Salmón", categoryId: "entradas", precio: 745 },
  { id: "carpaccio-res", nombre: "Carpaccio de Res", categoryId: "entradas", precio: 765 },
  { id: "lambi-vinagreta", nombre: "Lambí a la Vinagreta", categoryId: "entradas", precio: 695 },
  { id: "coctel-camarones", nombre: "Cóctel de Camarones", categoryId: "entradas", precio: 850 },
  { id: "tabla-quesos", nombre: "Tabla de Quesos e Ibérico", categoryId: "entradas", precio: 1550, descripcion: "Queso Manchego, ibérico curado, queso de cabra, jamón serrano, aceitunas, pan y mermelada" },

  { id: "chivo-del-valle", nombre: "Chivo del Valle", categoryId: "especialidades", precio: 960, descripcion: "Cocido en salsa de la casa. Guarnición de preferencia incluida.", destacado: true, incluyeGuarnicion: true },
  { id: "conejo", nombre: "Conejo", categoryId: "especialidades", precio: 990, descripcion: "A la parrilla, toque de romero. Guarnición incluida.", destacado: true, incluyeGuarnicion: true },
  { id: "gallina-criolla", nombre: "Gallina Criolla", categoryId: "especialidades", precio: 895, descripcion: "Cocida en salsa de la casa. Guarnición incluida.", destacado: true, incluyeGuarnicion: true },

  { id: "pechuga-parrilla", nombre: "Pechuga a la Parrilla", categoryId: "cortes", precio: 650, incluyeGuarnicion: true },
  { id: "pechuga-salsa-rey", nombre: "Pechuga a la Parrilla terminada en Salsa del Rey", categoryId: "cortes", precio: 770, incluyeGuarnicion: true },
  { id: "filete-cerdo-parrilla", nombre: "Filete de Cerdo a la Parrilla", categoryId: "cortes", precio: 760, incluyeGuarnicion: true },
  { id: "filete-cerdo-mostaza", nombre: "Filete de Cerdo en Salsa de Mostaza y Especias", categoryId: "cortes", precio: 860, incluyeGuarnicion: true },
  { id: "costillas-bbq", nombre: "Costillas de Cerdo terminadas con Salsa BBQ de la Casa", categoryId: "cortes", precio: 895, destacado: true, incluyeGuarnicion: true },
  { id: "bistec-encebollado", nombre: "Bistec Encebollado con Toque de Vino Tinto", categoryId: "cortes", precio: 790, destacado: true, incluyeGuarnicion: true },
  { id: "filete-res-parrilla", nombre: "Filete de Res a la Parrilla", categoryId: "cortes", precio: 900, incluyeGuarnicion: true },
  { id: "filete-res-queso-azul", nombre: "Filete de Res terminado en Salsa de Queso Azul", categoryId: "cortes", precio: 990, incluyeGuarnicion: true },
  { id: "churrasco-angus", nombre: "Churrasco Angus a la Parrilla (8 oz)", categoryId: "cortes", precio: 1990, incluyeGuarnicion: true },
  { id: "flap-meat", nombre: "Flap Meat Angus a la Parrilla (8 oz)", categoryId: "cortes", precio: 1895, incluyeGuarnicion: true },
  { id: "ribeye", nombre: "Ribeye a la Parrilla en Salsa de Finas Hierbas (8 oz)", categoryId: "cortes", precio: 2295, incluyeGuarnicion: true },
  { id: "pechuga-crema", nombre: "Pechuga a la Crema", categoryId: "cortes", precio: null, incluyeGuarnicion: true },

  { id: "ensalada-constancera", nombre: "Ensalada Constancera", categoryId: "ensaladas", precio: 350, descripcion: "Lechuga, tomate, pepino y zanahoria" },
  { id: "ensalada-cesar", nombre: "Ensalada César con Pollo", categoryId: "ensaladas", precio: 600 },
  { id: "ensalada-capressa", nombre: "Ensalada Capressa", categoryId: "ensaladas", precio: 500 },
  { id: "ensalada-mar", nombre: "Ensalada del Mar", categoryId: "ensaladas", precio: 1095, descripcion: "Mix de mariscos de temporada" },

  { id: "sancocho", nombre: "Sancocho Clásico", categoryId: "caldos", precio: 795, descripcion: "Tres carnes y mix de tubérculos, con arroz blanco", destacado: true },
  { id: "caldo-pollo", nombre: "Caldo de Pollo y Vegetales", categoryId: "caldos", precio: 650 },
  { id: "caldo-mar", nombre: "Caldo del Mar", categoryId: "caldos", precio: 1125, descripcion: "Mariscos y trocitos de salmón, con tostones o arroz" },

  { id: "bastoncitos-pollo", nombre: "Bastoncitos de Pollo", categoryId: "picaderas", precio: 550 },
  { id: "canastitas-pollo", nombre: "Canastitas de Pollo", categoryId: "picaderas", precio: 650, descripcion: "A la parrilla o a la crema" },
  { id: "canastitas-camarones", nombre: "Canastitas de Camarones", categoryId: "picaderas", precio: 885, descripcion: "Parrilla, crema o ajillo" },
  { id: "carne-salada", nombre: "Carne Salada", categoryId: "picaderas", precio: 625 },
  { id: "salchicha-parrillera", nombre: "Salchicha Parrillera", categoryId: "picaderas", precio: 500 },
  { id: "hamburguesa-especial", nombre: "Hamburguesa Especial con Bacon", categoryId: "picaderas", precio: 695, descripcion: "Res, queso, vegetales, bacon y papas fritas" },
  { id: "hamburguesa-pollo", nombre: "Hamburguesa de Pollo", categoryId: "picaderas", precio: 645, descripcion: "Pechuga a la parrilla y papas fritas" },
  { id: "tabla-mixta", nombre: "Tabla Mixta VDV para 4 Personas", categoryId: "picaderas", precio: 2995, descripcion: "Cerdo, pollo, res y salchicha" },

  { id: "pasta-alfredo-pollo", nombre: "Pasta Alfredo con Pollo", categoryId: "pastas", precio: 650, descripcion: "Espagueti, penne o linguini" },
  { id: "pasta-alfredo-camarones", nombre: "Pasta Alfredo con Camarones", categoryId: "pastas", precio: 995 },
  { id: "pasta-tomate", nombre: "Pasta de Tomates Frescos y Toque de Parmesano", categoryId: "pastas", precio: 500 },
  { id: "pasta-tomate-camarones", nombre: "Pasta de Tomates Frescos con Camarones", categoryId: "pastas", precio: 975 },
  { id: "pasta-4-quesos", nombre: "Pasta 4 Quesos", categoryId: "pastas", precio: 595 },
  { id: "pasta-tocineta", nombre: "Pasta con Tocineta y Parmesano", categoryId: "pastas", precio: 675 },
  { id: "pasta-marinera", nombre: "Pasta a la Marinera", categoryId: "pastas", precio: 1195, descripcion: "Camarones, salmón, calamar, mejillones, salsa de tomates frescos" },
  { id: "pasta-crema-blanca", nombre: "Pasta en Crema Blanca", categoryId: "pastas", precio: null },
  { id: "pan-tostado", nombre: "Pan Tostado", categoryId: "pastas", precio: null },

  { id: "arroz-mariscos", nombre: "Arroz con Mariscos Mixtos", categoryId: "arroces", precio: 1095, descripcion: "Acompañado de ensalada constancera" },
  { id: "asopao-camarones", nombre: "Asopao de Camarones", categoryId: "arroces", precio: 960 },
  { id: "asopao-mariscos", nombre: "Asopao de Mariscos Mixtos", categoryId: "arroces", precio: 1050 },

  { id: "salmon-parrilla", nombre: "Salmón Fresco a la Parrilla", categoryId: "pescados", precio: 1075, incluyeGuarnicion: true },
  { id: "salmon-bosque", nombre: "Salmón a la Parrilla terminado en Salsa del Bosque", categoryId: "pescados", precio: 1195, incluyeGuarnicion: true },
  { id: "camarones-almendras", nombre: "Camarones Rostizados en Salsa de Almendras", categoryId: "pescados", precio: 995, incluyeGuarnicion: true },
  { id: "camarones-ajillo", nombre: "Camarones al Ajillo", categoryId: "pescados", precio: 960, incluyeGuarnicion: true },
  { id: "camarones-crema", nombre: "Camarones terminados en Crema Blanca", categoryId: "pescados", precio: 960, incluyeGuarnicion: true },
  { id: "lambi-plato", nombre: "Lambí (vinagreta o criolla)", categoryId: "pescados", precio: 950, incluyeGuarnicion: true },
  { id: "lambi-criolla", nombre: "Lambí a la Criolla", categoryId: "pescados", precio: 950, incluyeGuarnicion: true },
  { id: "camarones-criolla", nombre: "Camarones a la Criolla", categoryId: "pescados", precio: null, incluyeGuarnicion: true },
  { id: "langostinos-bandera", nombre: "Langostinos a la Bandera", categoryId: "pescados", precio: 1550, descripcion: "Crema blanca, curry y especias, o al grill", incluyeGuarnicion: true },

  { id: "dulce-coco", nombre: "Dulce de Coco Tierno", categoryId: "postres", precio: 280 },
  { id: "majarete", nombre: "Majarete", categoryId: "postres", precio: 280 },
  { id: "quesillo-coco", nombre: "Quesillo de Coco", categoryId: "postres", precio: 260 },
  { id: "bizcocho-chocolate", nombre: "Bizcocho de Chocolate", categoryId: "postres", precio: 300 },
  { id: "helado", nombre: "Helado", categoryId: "postres", precio: 260 },
  { id: "bizcocho-moda", nombre: "Bizcocho a la Moda", categoryId: "postres", precio: null },
  { id: "bizcocho-sorpresa", nombre: "Bizcocho Sorpresa", categoryId: "postres", precio: null },
  { id: "quesillo-sorpresa", nombre: "Quesillo Sorpresa", categoryId: "postres", precio: null },

  { id: "tostones", nombre: "Tostones", categoryId: "guarniciones", precio: null },
  { id: "casabe", nombre: "Casabe Tostado", categoryId: "guarniciones", precio: null },
  { id: "papas-fritas", nombre: "Papas Fritas", categoryId: "guarniciones", precio: null },
  { id: "papas-salteadas", nombre: "Papas Salteadas", categoryId: "guarniciones", precio: null },
  { id: "aguacate", nombre: "Aguacate", categoryId: "guarniciones", precio: null },
  { id: "vegetales-grill", nombre: "Vegetales al Grill", categoryId: "guarniciones", precio: null },
  { id: "yuca-frita", nombre: "Yuca Frita", categoryId: "guarniciones", precio: null },
  { id: "tostones-maduro", nombre: "Tostones de Maduro", categoryId: "guarniciones", precio: null },
  { id: "pure-papa", nombre: "Puré de Papas", categoryId: "guarniciones", precio: null },
  { id: "chips-yautia", nombre: "Chips de Yautía Coco", categoryId: "guarniciones", precio: null },
  { id: "pure-cepa", nombre: "Puré de Cepa de Apio", categoryId: "guarniciones", precio: null },
  { id: "moro-guandules", nombre: "Moro de Guandules", categoryId: "guarniciones", precio: null },
  { id: "arroz-blanco", nombre: "Arroz Blanco", categoryId: "guarniciones", precio: null },
  { id: "habichuelas", nombre: "Habichuelas Guisadas", categoryId: "guarniciones", precio: null },
  { id: "guandules-guisados", nombre: "Guandules Guisados", categoryId: "guarniciones", precio: null },
  { id: "tostones-cepa", nombre: "Tostones de Cepa de Apio", categoryId: "guarniciones", precio: null },

  { id: "desayuno-dominicano", nombre: "Desayuno Clásico Dominicano", categoryId: "desayunos", precio: null },
  { id: "desayuno-americano", nombre: "Desayuno Americano", categoryId: "desayunos", precio: null },
  { id: "omelette", nombre: "Omelette con Pan Tostado", categoryId: "desayunos", precio: null },
  { id: "tostada-rustica", nombre: "Tostada Rústica de la Casa", categoryId: "desayunos", precio: null },
  { id: "el-ligero", nombre: "El Ligero", categoryId: "desayunos", precio: null },
  { id: "sandwich-jamon-queso", nombre: "Sándwich Jamón y Queso Mozzarella", categoryId: "desayunos", precio: null },
  { id: "derretido-queso", nombre: "Derretido de Queso", categoryId: "desayunos", precio: null },
  { id: "croissant", nombre: "Croissant Clásico", categoryId: "desayunos", precio: null },
  { id: "huevos-estrellados", nombre: "Huevos Estrellados", categoryId: "desayunos", precio: null },
  { id: "croissant-jamon", nombre: "Croissant Jamón y Queso", categoryId: "desayunos", precio: null },

  { id: "jugo-chinola", nombre: "Jugo de Chinola", categoryId: "jugos" },
  { id: "jugo-limon", nombre: "Jugo de Limón", categoryId: "jugos" },
  { id: "jugo-fresa", nombre: "Jugo de Fresa", categoryId: "jugos" },
  { id: "jugo-cereza", nombre: "Jugo de Cereza", categoryId: "jugos" },
  { id: "jugo-pina", nombre: "Jugo de Piña", categoryId: "jugos" },
  { id: "jugo-naranja", nombre: "Jugo de Naranja", categoryId: "jugos" },
  { id: "tamarindo", nombre: "Tamarindo", categoryId: "jugos" },
  { id: "lechosa-leche", nombre: "Lechosa con Leche", categoryId: "jugos" },
  { id: "jugo-lechosa", nombre: "Jugo de Lechosa", categoryId: "jugos" },
  { id: "morir-chinola", nombre: "Morir Soñando de Chinola", categoryId: "jugos" },
  { id: "morir-naranja", nombre: "Morir Soñando de Naranja", categoryId: "jugos" },
  { id: "morir-limon", nombre: "Morir Soñando de Limón", categoryId: "jugos" },
  { id: "frozen-fresa", nombre: "Frozen de Fresa", categoryId: "jugos" },
  { id: "frozen-chinola", nombre: "Frozen de Chinola", categoryId: "jugos" },
  { id: "frozen-limon", nombre: "Frozen de Limón", categoryId: "jugos" },
  { id: "frozen-limon-menta", nombre: "Frozen de Limón con Menta", categoryId: "jugos" },
  { id: "fresa-leche", nombre: "Fresa con Leche", categoryId: "jugos" },
  { id: "jugo-limon-menta", nombre: "Jugo Limón Menta", categoryId: "jugos" },
  { id: "frozen-fresa-limon", nombre: "Frozen Fresa con Limón", categoryId: "jugos" },
  { id: "chinola-fresa-frozen", nombre: "Chinola con Fresa Frozen", categoryId: "jugos" },
  { id: "jugo-melon", nombre: "Jugo de Melón", categoryId: "jugos" },
  { id: "jugo-fresa-limon", nombre: "Jugo Fresa Limón", categoryId: "jugos" },
  { id: "mezcla-frutas", nombre: "Mezcla Frutas", categoryId: "jugos" },

  { id: "cafe-negro", nombre: "Café Negro", categoryId: "cafes" },
  { id: "cafe-crema", nombre: "Café con Crema", categoryId: "cafes" },
  { id: "cafe-leche", nombre: "Café con Leche", categoryId: "cafes" },
  { id: "cortadito", nombre: "Cortadito", categoryId: "cafes" },
  { id: "expresso", nombre: "Expresso", categoryId: "cafes" },
  { id: "expresso-doble", nombre: "Expresso Doble", categoryId: "cafes" },
  { id: "frappe", nombre: "Frappe", categoryId: "cafes" },
  { id: "chocolate-leche", nombre: "Chocolate con Leche", categoryId: "cafes" },
  { id: "te-jengibre", nombre: "Té de la Casa con Jengibre", categoryId: "cafes" },
  { id: "te-frio", nombre: "Té Frío", categoryId: "cafes" },
  { id: "cafe-leche-almendra", nombre: "Café con Leche Almendra", categoryId: "cafes" },
  { id: "leche-extra", nombre: "Leche Extra", categoryId: "cafes" },
  { id: "chocolate-agua", nombre: "Chocolate de Agua", categoryId: "cafes" },
  { id: "taza-leche", nombre: "Taza de Leche Entera", categoryId: "cafes" },

  { id: "presidente", nombre: "Presidente Normal", categoryId: "cervezas" },
  { id: "presidente-light", nombre: "Presidente Light", categoryId: "cervezas" },
  { id: "corona-extra", nombre: "Corona Extra", categoryId: "cervezas" },
  { id: "corona-zero", nombre: "Corona Zero", categoryId: "cervezas" },
  { id: "modelo-especial", nombre: "Modelo Especial Rubia", categoryId: "cervezas" },
  { id: "modelo-negra", nombre: "Modelo Negra", categoryId: "cervezas" },
  { id: "bohemia", nombre: "Bohemia", categoryId: "cervezas" },
  { id: "heineken", nombre: "Heineken", categoryId: "cervezas" },
  { id: "heineken-grande", nombre: "Heineken Grande", categoryId: "cervezas" },
  { id: "heineken-cero", nombre: "Heineken Cero", categoryId: "cervezas" },
  { id: "stella", nombre: "Stella Artois", categoryId: "cervezas" },
  { id: "paulaner-dunkel", nombre: "Paulaner Negra Dunkel", categoryId: "cervezas" },
  { id: "paulaner-grande", nombre: "Paulaner Grande Rubia", categoryId: "cervezas" },
  { id: "paulaner-pequena", nombre: "Paulaner Pequeña Rubia", categoryId: "cervezas" },
  { id: "paulaner-sin", nombre: "Paulaner sin Alcohol", categoryId: "cervezas" },
  { id: "blue-moon", nombre: "Blue Moon Belgian", categoryId: "cervezas" },
  { id: "miller", nombre: "Miller Draft", categoryId: "cervezas" },
  { id: "smirnoff-ice", nombre: "Smirnoff Ice", categoryId: "cervezas" },
  { id: "smirnoff-green", nombre: "Smirnoff Green Apple", categoryId: "cervezas" },
  { id: "erdinger-dunkel", nombre: "Erdinger Dunkel", categoryId: "cervezas" },
  { id: "erdinger-rubia", nombre: "Erdinger Rubia", categoryId: "cervezas" },

  { id: "sangria-roja", nombre: "Sangría Roja", categoryId: "cocteles" },
  { id: "aperol-spritz", nombre: "Aperol Spritz", categoryId: "cocteles" },
  { id: "pina-colada-sin", nombre: "Piña Colada sin Alcohol", categoryId: "cocteles" },
  { id: "pina-colada", nombre: "Piña Colada con Alcohol", categoryId: "cocteles" },
  { id: "brisa-del-valle", nombre: "Brisa del Valle", categoryId: "cocteles" },
  { id: "mojito-coco", nombre: "Mojito Coco", categoryId: "cocteles" },
  { id: "mojito-chinola", nombre: "Mojito Chinola", categoryId: "cocteles" },
  { id: "mojito-fresa", nombre: "Mojito Fresa", categoryId: "cocteles" },
  { id: "mojito-limon", nombre: "Mojito Limón", categoryId: "cocteles" },
  { id: "negroni", nombre: "Negroni", categoryId: "cocteles" },
  { id: "expresso-martini", nombre: "Expresso Martini", categoryId: "cocteles" },
  { id: "gin-tonic-bombay", nombre: "Gin Tonic Bombay", categoryId: "cocteles" },
  { id: "caipirinha", nombre: "Caipirinha", categoryId: "cocteles" },
  { id: "margarita-fresa", nombre: "Margarita Frozen Fresa", categoryId: "cocteles" },
  { id: "margarita-clasica", nombre: "Margarita Clásica", categoryId: "cocteles" },
  { id: "gin-tonic-especiado", nombre: "Gin Tonic Especiado", categoryId: "cocteles" },
  { id: "gin-tonic-afrutado", nombre: "Gin Tonic Afrutado", categoryId: "cocteles" },
  { id: "sangria-blanca", nombre: "Sangría Blanca", categoryId: "cocteles" },
  { id: "margarita-chinola", nombre: "Margarita Frozen Chinola", categoryId: "cocteles" },
  { id: "mimosa", nombre: "Mimosa", categoryId: "cocteles" },
  { id: "sangria-rosada", nombre: "Sangría Rosada", categoryId: "cocteles" },
  { id: "tentacion", nombre: "Tentación", categoryId: "cocteles" },
  { id: "tequila-sunrise", nombre: "Tequila Sunrise", categoryId: "cocteles" },
  { id: "gin-rosado-beefeater", nombre: "Gin Rosado Beefeater", categoryId: "cocteles" },
  { id: "gin-tonic-beefeater", nombre: "Gin Tonic Beefeater Clásico", categoryId: "cocteles" },
  { id: "cuba-libre", nombre: "Cuba Libre", categoryId: "cocteles" },
  { id: "bloody-mary", nombre: "Bloody Mary", categoryId: "cocteles" },
  { id: "long-island", nombre: "Long Island", categoryId: "cocteles" },
  { id: "john-collins", nombre: "John Collins", categoryId: "cocteles" },
  { id: "margarita-deluxe", nombre: "Margarita Deluxe", categoryId: "cocteles" },
  { id: "vodka-sol", nombre: "Vodka y Sol", categoryId: "cocteles" },

  { id: "agua", nombre: "Agua", categoryId: "refrescos" },
  { id: "coca-cola", nombre: "Coca Cola", categoryId: "refrescos" },
  { id: "coca-zero", nombre: "Coca Cola Zero", categoryId: "refrescos" },
  { id: "sprite", nombre: "Sprite", categoryId: "refrescos" },
  { id: "club-soda", nombre: "Club Soda", categoryId: "refrescos" },
  { id: "ginger-ale", nombre: "Ginger Ale", categoryId: "refrescos" },
  { id: "tonica", nombre: "Tónica", categoryId: "refrescos" },
  { id: "perrier", nombre: "Perrier", categoryId: "refrescos" },
  { id: "san-pellegrino-1l", nombre: "San Pellegrino 1L", categoryId: "refrescos" },
  { id: "san-pellegrino-250", nombre: "San Pellegrino 250ml", categoryId: "refrescos" },
  { id: "red-bull", nombre: "Red Bull", categoryId: "refrescos" },
  { id: "clamato", nombre: "Clamato", categoryId: "refrescos" },

  { id: "micky-mouse", nombre: "Micky Mouse", categoryId: "ninos" },
  { id: "ocean-blue", nombre: "Ocean Blue", categoryId: "ninos" },

  { id: "copa-tinto", nombre: "Copa Vino Tinto", categoryId: "vinos" },
  { id: "copa-blanco", nombre: "Copa Vino Blanco", categoryId: "vinos" },
  { id: "navigator-cab", nombre: "Navigator Cab. Sauv.", categoryId: "vinos", precio: 2150, descripcion: "Tinto · Estados Unidos" },
  { id: "pra-vinera-tinto", nombre: "Pra Vinera Reserva", categoryId: "vinos", precio: 1750, descripcion: "Tinto · Estados Unidos" },
  { id: "motif-cab", nombre: "Motif Cab. Sauv.", categoryId: "vinos", precio: 1500, descripcion: "Tinto · Estados Unidos" },
  { id: "apothic-red", nombre: "Apothic Red", categoryId: "vinos", precio: 1900, descripcion: "Tinto · Estados Unidos" },
  { id: "six-eight-nine", nombre: "Six Eight Nine (689)", categoryId: "vinos", precio: 2150, descripcion: "Tinto · Estados Unidos" },
  { id: "bogle-essential", nombre: "Bogle Essential Red", categoryId: "vinos", precio: 2000, descripcion: "Tinto · Estados Unidos" },
  { id: "bogle-cab", nombre: "Bogle Cab. Sauv.", categoryId: "vinos", precio: 2150, descripcion: "Tinto · Estados Unidos" },
  { id: "altun-tempranillo", nombre: "Altun Tempranillo", categoryId: "vinos", precio: 1795, descripcion: "Tinto · España" },
  { id: "nabal-crianza", nombre: "Nabal Crianza", categoryId: "vinos", precio: 3600, descripcion: "Tinto · España" },
  { id: "nabal-reserva", nombre: "Nabal Reserva", categoryId: "vinos", precio: 5800, descripcion: "Tinto · España" },
  { id: "arroyo-gran-reserva", nombre: "Arroyo Gran Reserva", categoryId: "vinos", precio: 3900, descripcion: "Tinto · España" },
  { id: "alma-serena", nombre: "Alma Serena Reserva", categoryId: "vinos", precio: 2100, descripcion: "Tinto · España" },
  { id: "goru", nombre: "Goru", categoryId: "vinos", precio: 1195, descripcion: "Tinto · España" },
  { id: "protos-roble", nombre: "Protos Roble Ribera del Duero", categoryId: "vinos", precio: 1850, descripcion: "Tinto · España" },
  { id: "protos-crianza", nombre: "Protos Crianza", categoryId: "vinos", precio: 2800, descripcion: "Tinto · España" },
  { id: "glorioso-crianza", nombre: "Glorioso Crianza", categoryId: "vinos", precio: 1550, descripcion: "Tinto · España" },
  { id: "ruffino-chianti", nombre: "Ruffino Chianti", categoryId: "vinos", precio: 1700, descripcion: "Tinto · Italia" },
  { id: "crimes-red", nombre: "19 Crimes Red Wine", categoryId: "vinos", precio: 2000, descripcion: "Tinto · Australia" },
  { id: "palo-alto-cab", nombre: "Palo Alto Cab. Sauv.", categoryId: "vinos", precio: 1150, descripcion: "Tinto · Chile" },
  { id: "silk-spice", nombre: "Silk & Spice Red Blend", categoryId: "vinos", precio: 1250, descripcion: "Tinto · Portugal" },
  { id: "pra-chardonnay", nombre: "Pra Vinera Reserva", categoryId: "vinos", precio: 1750, descripcion: "Blanco · Estados Unidos" },
  { id: "beringer-pinot", nombre: "Beringer Pinot Grigio", categoryId: "vinos", precio: 1100, descripcion: "Blanco · Estados Unidos" },
  { id: "la-carmina-albarino", nombre: "La Carmina Albariño", categoryId: "vinos", precio: 1900, descripcion: "Blanco · España" },
  { id: "protos-verdejo", nombre: "Protos Verdejo", categoryId: "vinos", precio: 1750, descripcion: "Blanco · España" },
  { id: "tavo-pinot", nombre: "Tavo Pinot Grigio", categoryId: "vinos", precio: 1400, descripcion: "Blanco · Italia" },
  { id: "crimes-rose", nombre: "19 Crimes Cali Rosé", categoryId: "vinos", precio: 2000, descripcion: "Rosado" },
  { id: "beringer-white-zin", nombre: "Beringer White Zinfandel", categoryId: "vinos", precio: 1100, descripcion: "Rosado" },
  { id: "paul-cheneau", nombre: "Paul Cheneau Millésime Cava", categoryId: "vinos", precio: 1900, descripcion: "Espumante" },
  { id: "ilauri-prosecco", nombre: "Ilauri Prosecco", categoryId: "vinos", precio: 1895, descripcion: "Espumante" },
  { id: "ilauri-rose", nombre: "Ilauri Rosé", categoryId: "vinos", precio: 1895, descripcion: "Espumante" },
  { id: "bernard-remy", nombre: "Bernard Rémy Carte Blanche", categoryId: "vinos", precio: 4400, descripcion: "Champagne" },
  { id: "segura-viudas", nombre: "Segura Viudas Brut Reserva", categoryId: "vinos", precio: 1750, descripcion: "Espumante" },
  { id: "segura-viudas-rose", nombre: "Segura Viudas Brut Rosé", categoryId: "vinos", precio: 1700, descripcion: "Espumante" },

  { id: "aperol", nombre: "Aperol", categoryId: "licores", precio: 270, descripcion: "Aperitivo" },
  { id: "campari", nombre: "Campari", categoryId: "licores", precio: 295, descripcion: "Aperitivo" },
  { id: "tia-maria", nombre: "Tía María", categoryId: "licores", precio: 220, descripcion: "Licor" },
  { id: "baileys", nombre: "Baileys", categoryId: "licores", precio: 305, descripcion: "Licor" },
  { id: "kahlua", nombre: "Kahlúa", categoryId: "licores", precio: 330, descripcion: "Licor" },
  { id: "cointreau", nombre: "Cointreau", categoryId: "licores", precio: 395, descripcion: "Licor" },
  { id: "disaronno", nombre: "Amaretto Disaronno", categoryId: "licores", precio: 355, descripcion: "Digestivo" },
  { id: "amaro-averna", nombre: "Amaro Averna", categoryId: "licores", precio: 295, descripcion: "Digestivo" },
  { id: "limoncello", nombre: "Limoncello Cellini", categoryId: "licores", precio: 290, descripcion: "Digestivo" },
  { id: "grappa-cellini", nombre: "Grappa Cellini", categoryId: "licores", precio: 290, descripcion: "Digestivo" },
  { id: "sambuca-bottega", nombre: "Sambuca Bottega", categoryId: "licores", precio: 290, descripcion: "Digestivo" },
  { id: "fernet", nombre: "Fernet Branca", categoryId: "licores", precio: 300, descripcion: "Digestivo" },
  { id: "fernet-menta", nombre: "Fernet Branca Menta", categoryId: "licores", precio: 300, descripcion: "Digestivo" },
  { id: "remy-martin-vsop", nombre: "Rémy Martin VSOP", categoryId: "licores", precio: 725, descripcion: "Cognac" },
  { id: "cardenal-mendoza", nombre: "Cardenal Mendoza", categoryId: "licores", precio: 550, descripcion: "Brandy" },
  { id: "ginebra", nombre: "Beefeater", categoryId: "licores", precio: 285, descripcion: "Ginebra" },
  { id: "beefeater-rosada", nombre: "Beefeater Rosada", categoryId: "licores", precio: 295, descripcion: "Ginebra" },
  { id: "bombay", nombre: "Bombay", categoryId: "licores", precio: 345, descripcion: "Ginebra" },
  { id: "smirnoff", nombre: "Smirnoff", categoryId: "licores", precio: 250, descripcion: "Vodka" },
  { id: "stolichnaya", nombre: "Stolichnaya", categoryId: "licores", precio: 260, descripcion: "Vodka" },
  { id: "absolut", nombre: "Absolut", categoryId: "licores", precio: 280, descripcion: "Vodka" },
  { id: "grey-goose", nombre: "Grey Goose", categoryId: "licores", precio: 405, descripcion: "Vodka" },
  { id: "jose-cuervo", nombre: "José Cuervo Blanca o Dorada", categoryId: "licores", precio: 320, descripcion: "Tequila" },
  { id: "patron-silver", nombre: "Patrón Silver", categoryId: "licores", precio: 630, descripcion: "Tequila" },
  { id: "huizar-reposado", nombre: "Huizar Reposado", categoryId: "licores", precio: 655, descripcion: "Tequila" },
  { id: "mi-familia-flores", nombre: "Mi Familia Flores", categoryId: "licores", precio: 650, descripcion: "Tequila" },
  { id: "jw-black", nombre: "Johnnie W. Black Label", categoryId: "licores", precio: 480, descripcion: "Whisky" },
  { id: "jw-double-black", nombre: "Johnnie W. Double Black", categoryId: "licores", precio: 585, descripcion: "Whisky" },
  { id: "jack-daniels", nombre: "Jack Daniel's No.7", categoryId: "licores", precio: 350, descripcion: "Whisky" },
  { id: "fireball", nombre: "Fireball", categoryId: "licores", precio: 320, descripcion: "Whisky" },
  { id: "dewars", nombre: "Dewar's White Label 8 años", categoryId: "licores", precio: 220, descripcion: "Whisky" },
  { id: "buchanans-12", nombre: "Buchanan's 12 años", categoryId: "licores", precio: 495, descripcion: "Whisky" },
  { id: "old-parr", nombre: "Old Parr 12 años", categoryId: "licores", precio: 450, descripcion: "Whisky" },
  { id: "chivas-12", nombre: "Chivas Regal 12 años", categoryId: "licores", precio: 470, descripcion: "Whisky" },
  { id: "glenlivet-12", nombre: "The Glenlivet 12 años", categoryId: "licores", precio: 450, descripcion: "Whisky" },
  { id: "macallan-12", nombre: "The Macallan Double Cask 12 años", categoryId: "licores", precio: 855, descripcion: "Whisky" },
  { id: "tomatin-legacy", nombre: "Tomatin Legacy", categoryId: "licores", precio: 520, descripcion: "Whisky" },
  { id: "barcelo-gran-anejo", nombre: "Barceló Gran Añejo", categoryId: "licores", precio: 200, descripcion: "Ron" },
  { id: "barcelo-imperial", nombre: "Barceló Imperial", categoryId: "licores", precio: 325, descripcion: "Ron" },
  { id: "barcelo-blanco", nombre: "Barceló Blanco", categoryId: "licores" },
  { id: "doble-reserva", nombre: "Brugal Doble Reserva", categoryId: "licores", precio: 250, descripcion: "Ron" },
  { id: "brugal-triple", nombre: "Brugal Triple Reserva", categoryId: "licores", precio: 275, descripcion: "Ron" },
  { id: "brugal-extra-viejo", nombre: "Brugal Extra Viejo", categoryId: "licores", precio: 210, descripcion: "Ron" },
  { id: "brugal-xv", nombre: "Brugal XV", categoryId: "licores", precio: 220, descripcion: "Ron" },
  { id: "brugal-leyenda", nombre: "Brugal Leyenda", categoryId: "licores", precio: 325, descripcion: "Ron" },
  { id: "brugal-1888", nombre: "Brugal 1888", categoryId: "licores", precio: 465, descripcion: "Ron" },
  { id: "don-julio", nombre: "Don Julio Reposado", categoryId: "licores" },

  { id: "emp-hamburguesa", nombre: "Hamburguesa Especial (empleado)", categoryId: "emp-comida" },
  { id: "emp-sancocho", nombre: "Sancocho (empleado)", categoryId: "emp-comida" },
  { id: "emp-bistec", nombre: "Bistec Encebollado (empleado)", categoryId: "emp-comida" },
  { id: "emp-caldo-pollo", nombre: "Caldo de Pollo (empleado)", categoryId: "emp-comida" },
  { id: "emp-croquetas", nombre: "Croquetas de Pollo (empleado)", categoryId: "emp-comida" },
  { id: "emp-filete", nombre: "Filete a la Parrilla (empleado)", categoryId: "emp-comida" },
  { id: "emp-pechuga", nombre: "Pechuga a la Parrilla (empleado)", categoryId: "emp-comida" },
  { id: "emp-salchicha", nombre: "Salchicha (empleado)", categoryId: "emp-comida" },
  { id: "emp-agua", nombre: "Agua (empleado)", categoryId: "emp-bebida" },
  { id: "emp-coca", nombre: "Coca Cola (empleado)", categoryId: "emp-bebida" },
  { id: "emp-soda-amarga", nombre: "Soda amarga (empleado)", categoryId: "emp-bebida" },
  { id: "emp-flan", nombre: "Flan (empleado)", categoryId: "emp-comida" },
  { id: "emp-presidente", nombre: "Presidente (empleado)", categoryId: "emp-bebida" },
  { id: "emp-sprite", nombre: "Sprite (empleado)", categoryId: "emp-bebida" },
  { id: "hue-dominicano", nombre: "Desayuno Dominicano (huésped)", categoryId: "huespedes" },
  { id: "hue-sandwich", nombre: "Sándwich Jamón y Queso (huésped)", categoryId: "huespedes" },
  { id: "hue-cafe", nombre: "Café Negro (huésped)", categoryId: "huespedes" },
  { id: "hue-agua", nombre: "Agua (huésped)", categoryId: "huespedes" },
  { id: "hue-chinola", nombre: "Jugo de Chinola (huésped)", categoryId: "huespedes" },
  { id: "hue-limon", nombre: "Jugo de Limón (huésped)", categoryId: "huespedes" },
  { id: "almuerzo-ejecutivo", nombre: "Almuerzo Ejecutivo", categoryId: "extras" },
  { id: "agua-llevar", nombre: "Agua para llevar", categoryId: "extras" },
  { id: "zumo-limon", nombre: "Zumo de limón", categoryId: "extras" },
  { id: "extra-huevo", nombre: "Huevo Extra", categoryId: "extras" },
  { id: "extra-parmesano", nombre: "Parmesano Extra", categoryId: "extras" },
  { id: "extra-tocineta", nombre: "Extra Tocineta", categoryId: "extras" },
  { id: "extra-mozzarella", nombre: "Queso Mozzarella Extra", categoryId: "extras" },
  { id: "extra-pollo", nombre: "Extra Pollo", categoryId: "extras" },
  { id: "extra-salami", nombre: "Salami Extra", categoryId: "extras" },
  { id: "salsa-crema", nombre: "Salsa a la Crema", categoryId: "extras" },
  { id: "vaso-plastico", nombre: "Vaso Plástico", categoryId: "extras" },
  { id: "b52", nombre: "B-52", categoryId: "extras" },
  { id: "descorche", nombre: "Descorche", categoryId: "extras" },
  { id: "descorche-chivas", nombre: "Descorche de Chivas", categoryId: "extras" },
  { id: "extra-leche-almendra", nombre: "Extra leche almendra", categoryId: "extras" },
  { id: "vaso-hielo", nombre: "Vaso con hielo", categoryId: "extras" },
  { id: "vela-cumple", nombre: "Vela de cumpleaños", categoryId: "extras" },
  { id: "aceitunas-extra", nombre: "Aceitunas rellenas (extra)", categoryId: "extras" },
];

export const ingredients: { id: string; nombre: string; unidad: Unidad; minimo: number }[] = [
  { id: "chivo", nombre: "Carne de chivo", unidad: "G", minimo: 2000 },
  { id: "conejo", nombre: "Carne de conejo", unidad: "G", minimo: 1500 },
  { id: "gallina", nombre: "Gallina criolla", unidad: "G", minimo: 1500 },
  { id: "bistec-res", nombre: "Bistec de res", unidad: "G", minimo: 2000 },
  { id: "filete-res", nombre: "Filete de res", unidad: "G", minimo: 2000 },
  { id: "churrasco", nombre: "Churrasco angus", unidad: "G", minimo: 1500 },
  { id: "flap-meat", nombre: "Flap meat angus", unidad: "G", minimo: 1000 },
  { id: "ribeye", nombre: "Ribeye", unidad: "G", minimo: 1000 },
  { id: "filete-cerdo", nombre: "Filete de cerdo", unidad: "G", minimo: 2000 },
  { id: "costilla-cerdo", nombre: "Costilla de cerdo", unidad: "G", minimo: 2000 },
  { id: "pechuga", nombre: "Pechuga de pollo", unidad: "G", minimo: 3000 },
  { id: "pollo", nombre: "Pollo (desmenuzado/caldo)", unidad: "G", minimo: 1000 },
  { id: "carne-molida", nombre: "Carne molida de res", unidad: "G", minimo: 1500 },
  { id: "carne-salada", nombre: "Carne salada", unidad: "G", minimo: 1000 },
  { id: "tocineta", nombre: "Tocineta / bacon", unidad: "G", minimo: 500 },
  { id: "salchicha", nombre: "Salchicha parrillera", unidad: "G", minimo: 1000 },
  { id: "jamon-serrano", nombre: "Jamón serrano", unidad: "G", minimo: 300 },
  { id: "salami", nombre: "Salami", unidad: "G", minimo: 300 },
  { id: "camarones", nombre: "Camarones", unidad: "G", minimo: 2000 },
  { id: "calamar", nombre: "Calamar (anillas)", unidad: "G", minimo: 1000 },
  { id: "mejillones", nombre: "Mejillones", unidad: "G", minimo: 500 },
  { id: "lambi", nombre: "Lambí", unidad: "G", minimo: 1000 },
  { id: "langostinos", nombre: "Langostinos", unidad: "G", minimo: 800 },
  { id: "salmon", nombre: "Salmón fresco", unidad: "G", minimo: 1500 },
  { id: "mix-mariscos", nombre: "Mix de mariscos", unidad: "G", minimo: 1000 },
  { id: "mozzarella", nombre: "Queso mozzarella", unidad: "G", minimo: 1000 },
  { id: "parmesano", nombre: "Parmesano", unidad: "G", minimo: 500 },
  { id: "queso-azul", nombre: "Queso azul", unidad: "G", minimo: 300 },
  { id: "gouda", nombre: "Queso gouda", unidad: "G", minimo: 300 },
  { id: "manchego", nombre: "Queso manchego", unidad: "G", minimo: 300 },
  { id: "iberico", nombre: "Queso ibérico curado", unidad: "G", minimo: 300 },
  { id: "queso-cabra", nombre: "Queso de cabra", unidad: "G", minimo: 300 },
  { id: "queso-crema", nombre: "Queso crema", unidad: "G", minimo: 500 },
  { id: "queso-cativia", nombre: "Queso para cativía", unidad: "G", minimo: 500 },
  { id: "crema-leche", nombre: "Crema de leche", unidad: "ML", minimo: 2000 },
  { id: "leche", nombre: "Leche entera", unidad: "ML", minimo: 2000 },
  { id: "leche-almendra", nombre: "Leche de almendra", unidad: "ML", minimo: 500 },
  { id: "mantequilla", nombre: "Mantequilla", unidad: "G", minimo: 500 },
  { id: "helado-vainilla", nombre: "Helado de vainilla", unidad: "ML", minimo: 2000 },
  { id: "lechuga", nombre: "Lechuga", unidad: "G", minimo: 1000 },
  { id: "tomate", nombre: "Tomate", unidad: "G", minimo: 2000 },
  { id: "pepino", nombre: "Pepino", unidad: "G", minimo: 500 },
  { id: "zanahoria", nombre: "Zanahoria", unidad: "G", minimo: 500 },
  { id: "cebolla", nombre: "Cebolla", unidad: "G", minimo: 2000 },
  { id: "pimiento", nombre: "Pimiento", unidad: "G", minimo: 500 },
  { id: "ajo", nombre: "Ajo", unidad: "G", minimo: 300 },
  { id: "apio", nombre: "Apio", unidad: "G", minimo: 300 },
  { id: "auyama", nombre: "Auyama", unidad: "G", minimo: 1000 },
  { id: "papa", nombre: "Papa", unidad: "G", minimo: 3000 },
  { id: "yuca", nombre: "Yuca", unidad: "G", minimo: 2000 },
  { id: "name", nombre: "Ñame", unidad: "G", minimo: 800 },
  { id: "platano-verde", nombre: "Plátano verde", unidad: "UD", minimo: 30 },
  { id: "platano-maduro", nombre: "Plátano maduro", unidad: "UD", minimo: 15 },
  { id: "yautia", nombre: "Yautía", unidad: "G", minimo: 1000 },
  { id: "cepa-apio", nombre: "Cepa de apio", unidad: "G", minimo: 800 },
  { id: "aguacate", nombre: "Aguacate", unidad: "UD", minimo: 15 },
  { id: "champinones", nombre: "Champiñones", unidad: "G", minimo: 500 },
  { id: "aceitunas", nombre: "Aceitunas rellenas", unidad: "G", minimo: 500 },
  { id: "pepinillos", nombre: "Pepinillos", unidad: "G", minimo: 300 },
  { id: "mazorca", nombre: "Mazorca", unidad: "UD", minimo: 10 },
  { id: "guandules", nombre: "Guandules", unidad: "G", minimo: 800 },
  { id: "habichuelas", nombre: "Habichuelas", unidad: "G", minimo: 1000 },
  { id: "limon", nombre: "Limón", unidad: "UD", minimo: 20 },
  { id: "chinola", nombre: "Chinola", unidad: "UD", minimo: 40 },
  { id: "fresa", nombre: "Fresa", unidad: "G", minimo: 2000 },
  { id: "naranja", nombre: "Naranja", unidad: "UD", minimo: 30 },
  { id: "pina", nombre: "Piña", unidad: "UD", minimo: 10 },
  { id: "cereza", nombre: "Cereza", unidad: "G", minimo: 1000 },
  { id: "lechosa", nombre: "Lechosa", unidad: "UD", minimo: 5 },
  { id: "tamarindo", nombre: "Tamarindo", unidad: "G", minimo: 800 },
  { id: "coco", nombre: "Coco", unidad: "UD", minimo: 10 },
  { id: "arroz", nombre: "Arroz", unidad: "G", minimo: 3000 },
  { id: "pasta", nombre: "Pasta (espagueti/penne/linguini)", unidad: "G", minimo: 3000 },
  { id: "harina", nombre: "Harina de trigo", unidad: "G", minimo: 2000 },
  { id: "pan-rallado", nombre: "Pan rallado", unidad: "G", minimo: 1000 },
  { id: "baguette", nombre: "Pan baguette", unidad: "UD", minimo: 5 },
  { id: "brioche", nombre: "Pan brioche", unidad: "UD", minimo: 15 },
  { id: "crutones", nombre: "Crutones", unidad: "G", minimo: 300 },
  { id: "casabe", nombre: "Casabe", unidad: "G", minimo: 500 },
  { id: "huevo", nombre: "Huevo", unidad: "UD", minimo: 60 },
  { id: "cafe", nombre: "Café molido", unidad: "G", minimo: 2000 },
  { id: "aceite-oliva", nombre: "Aceite de oliva", unidad: "ML", minimo: 1500 },
  { id: "aceite-freir", nombre: "Aceite para freír", unidad: "ML", minimo: 5000 },
  { id: "vinagre", nombre: "Vinagre", unidad: "ML", minimo: 500 },
  { id: "ketchup", nombre: "Ketchup", unidad: "ML", minimo: 1000 },
  { id: "mayonesa", nombre: "Mayonesa", unidad: "ML", minimo: 1000 },
  { id: "mostaza", nombre: "Mostaza dijon", unidad: "G", minimo: 300 },
  { id: "salsa-bbq", nombre: "Salsa BBQ", unidad: "ML", minimo: 1000 },
  { id: "aderezo-cesar", nombre: "Aderezo césar", unidad: "ML", minimo: 800 },
  { id: "vino-tinto", nombre: "Vino tinto (cocción)", unidad: "ML", minimo: 750 },
  { id: "vino-blanco", nombre: "Vino blanco (cocción)", unidad: "ML", minimo: 750 },
  { id: "curry", nombre: "Curry", unidad: "G", minimo: 100 },
  { id: "almendras", nombre: "Almendras", unidad: "G", minimo: 300 },
  { id: "sal", nombre: "Sal", unidad: "G", minimo: 500 },
  { id: "azucar", nombre: "Azúcar", unidad: "G", minimo: 1000 },
  { id: "albahaca", nombre: "Albahaca", unidad: "G", minimo: 100 },
  { id: "cilantro", nombre: "Cilantro", unidad: "G", minimo: 200 },
  { id: "perejil", nombre: "Perejil", unidad: "G", minimo: 100 },
  { id: "oregano", nombre: "Orégano", unidad: "G", minimo: 100 },
  { id: "romero", nombre: "Romero", unidad: "G", minimo: 100 },
  { id: "finas-hierbas", nombre: "Finas hierbas", unidad: "G", minimo: 100 },
  { id: "mermelada", nombre: "Mermelada", unidad: "G", minimo: 300 },
  { id: "chocolate", nombre: "Chocolate (postre)", unidad: "G", minimo: 500 },
  { id: "maiz", nombre: "Maíz / coco rallado (majarete)", unidad: "G", minimo: 500 },
  { id: "agua-ud", nombre: "Agua (botella)", unidad: "UD", minimo: 48 },
  { id: "presidente-ud", nombre: "Presidente normal (botella)", unidad: "UD", minimo: 24 },
  { id: "pimienta", nombre: "Pimienta", unidad: "G", minimo: 100 },
  { id: "aceite-crisol", nombre: "Aceite Crisol", unidad: "ML", minimo: 2000 },
  { id: "salsa-china", nombre: "Salsa china", unidad: "ML", minimo: 500 },
  { id: "salsa-pomodoro", nombre: "Salsa Pomodoro", unidad: "ML", minimo: 3785 },
  { id: "salsa-alfredo-blanca", nombre: "Salsa Alfredo blanca", unidad: "ML", minimo: 3785 },
  { id: "salsa-del-bosque", nombre: "Salsa del Bosque", unidad: "ML", minimo: 2000 },
  { id: "salsa-de-tamarindo", nombre: "Salsa de tamarindo", unidad: "ML", minimo: 3785 },
  { id: "salsa-al-ajillo", nombre: "Salsa al ajillo", unidad: "ML", minimo: 1000 },
  { id: "salsa-del-rey", nombre: "Salsa del Rey", unidad: "ML", minimo: 1000 },
  { id: "salsa-blue-cheese", nombre: "Salsa blue cheese", unidad: "ML", minimo: 1000 },
];

export type RecipeSeed = {
  dishId: string;
  minutos?: number;
  pasos: string[];
  items: [string, number][];
};

/** Recetas del cuaderno de cocina. Ningún otro plato debe tener receta. */
export const recipes: RecipeSeed[] = [
  { dishId: "tostones", minutos: 10, pasos: ["Freír, aplastar, volver a freír — 1 tostón por plato"], items: [["platano-verde", 1]] },
  { dishId: "casabe", minutos: 5, pasos: ["Tostar 1 lonja"], items: [["casabe", 60]] },
  { dishId: "papas-fritas", minutos: 12, pasos: ["Cortar y freír — 0.65 lb por servicio"], items: [["papa", 295]] },
  { dishId: "papas-salteadas", minutos: 12, pasos: ["Saltear 2 papas de tamaño normal"], items: [["papa", 300]] },
  { dishId: "aguacate", minutos: 2, pasos: ["Un aguacate rinde 2 servicios"], items: [["aguacate", 0.5]] },

  { dishId: "bistec-encebollado", minutos: 25, pasos: ["Sellar 8 oz de bistec", "Saltear 1 cebolla mediana", "Napar con 4 oz de salsa de tamarindo"], items: [["bistec-res", 227], ["cebolla", 150], ["salsa-de-tamarindo", 113], ["aceite-crisol", 28]] },
  { dishId: "arroz-mariscos", minutos: 35, pasos: ["Sofrito de morrón y cebolla", "Cocer 1/4 lb de arroz con 4 oz de salsa del Bosque", "Agregar 4 camarones y recorte de marisco"], items: [["arroz", 113], ["salsa-del-bosque", 113], ["camarones", 42], ["mix-mariscos", 85], ["aceite-crisol", 28], ["pimiento", 30], ["cebolla", 30]] },
  { dishId: "salmon-bosque", minutos: 22, pasos: ["Grillar 8 oz de salmón con ajo, sal, pimienta y limón", "Terminar con 4 oz de salsa del Bosque"], items: [["salmon", 227], ["salsa-del-bosque", 113], ["ajo", 5], ["sal", 2], ["pimienta", 1], ["limon", 0.25]] },
  { dishId: "canastitas-pollo", minutos: 25, pasos: ["Canasta de 1.5 plátanos", "Rellenar con 2 oz de pechuga (1/4 de porción de 8 oz)", "Salsa Alfredo / a la crema", "Vegetales: cebolla y morrón"], items: [["platano-verde", 1.5], ["pechuga", 57], ["aceite-crisol", 28], ["cebolla", 30], ["pimiento", 30], ["salsa-alfredo-blanca", 113]] },
  { dishId: "canastitas-camarones", minutos: 25, pasos: ["Misma canasta que pollo (1.5 plátanos, vegetales, aceite)", "6 camarones", "2 oz de salsa al ajillo (o Alfredo si es a la crema)"], items: [["platano-verde", 1.5], ["camarones", 62], ["aceite-crisol", 28], ["cebolla", 30], ["pimiento", 30], ["salsa-al-ajillo", 57]] },
  { dishId: "asopao-camarones", minutos: 30, pasos: ["Cocer 1/4 lb de arroz", "4 oz salsa Pomodoro + 4 oz salsa del Bosque", "8 camarones"], items: [["arroz", 113], ["salsa-pomodoro", 113], ["salsa-del-bosque", 113], ["camarones", 83]] },
  { dishId: "asopao-mariscos", minutos: 30, pasos: ["Cocer 1/4 lb de arroz", "4 oz salsa Pomodoro + 4 oz salsa del Bosque", "4 camarones y 3 oz de marisco"], items: [["arroz", 113], ["salsa-pomodoro", 113], ["salsa-del-bosque", 113], ["camarones", 42], ["mix-mariscos", 85]] },
  { dishId: "pasta-tomate", minutos: 20, pasos: ["Pasta con salsa Pomodoro", "3 cucharadas de parmesano"], items: [["pasta", 120], ["salsa-pomodoro", 113], ["parmesano", 15]] },
  { dishId: "pasta-tomate-camarones", minutos: 25, pasos: ["Pasta con salsa Pomodoro y camarones"], items: [["pasta", 120], ["salsa-pomodoro", 113], ["camarones", 52]] },
  { dishId: "pasta-tocineta", minutos: 20, pasos: ["Pasta con 1 rebanada de tocineta", "1 cucharada de parmesano"], items: [["pasta", 120], ["salsa-pomodoro", 113], ["tocineta", 20], ["parmesano", 5]] },
  { dishId: "pasta-alfredo-pollo", minutos: 25, pasos: ["Pasta con salsa Alfredo blanca (1 galón rinde 18 pastas)", "1/4 de porción de 8 oz de pechuga (2 oz)", "1 cucharada de parmesano"], items: [["pasta", 120], ["pechuga", 57], ["parmesano", 5], ["salsa-alfredo-blanca", 210]] },
  { dishId: "pasta-alfredo-camarones", minutos: 25, pasos: ["Pasta con salsa Alfredo blanca", "5 camarones (paquete de 42–45)", "1 cucharadita de parmesano"], items: [["pasta", 120], ["camarones", 52], ["parmesano", 3], ["salsa-alfredo-blanca", 210]] },
  { dishId: "filete-res-queso-azul", minutos: 25, pasos: ["Grillar 8 oz de res con ajo, sal y pimienta", "Napar con salsa blue cheese"], items: [["filete-res", 227], ["salsa-blue-cheese", 113], ["ajo", 5], ["sal", 3], ["pimienta", 1]] },
  { dishId: "filete-res-parrilla", minutos: 20, pasos: ["Igual que el filete en blue cheese", "La diferencia es salsa chimichurri (aún pendiente de receta)"], items: [["filete-res", 227], ["ajo", 5], ["sal", 3], ["pimienta", 1]] },
  { dishId: "pechuga-crema", minutos: 20, pasos: ["Grillar 8 oz de pechuga con ajo, sal, pimienta, orégano y mostaza", "Napar con salsa Alfredo (1 galón rinde 26 pechugas)"], items: [["pechuga", 227], ["salsa-alfredo-blanca", 146], ["ajo", 5], ["sal", 3], ["pimienta", 1], ["oregano", 2], ["mostaza", 5]] },
  { dishId: "pechuga-salsa-rey", minutos: 25, pasos: ["Grillar 8 oz de pechuga", "Salsa del Rey: morrón, cebolla, ají habanero, parmesano rallado y vino"], items: [["pechuga", 227], ["salsa-del-rey", 113], ["pimiento", 30], ["cebolla", 30], ["parmesano", 10]] },
  { dishId: "conejo", minutos: 50, pasos: ["Porción de conejo pendiente de confirmar — se usa 8 oz como los filetes", "Salsa de romero al instante: toque de vino + 1 rama de romero + salsa china"], items: [["conejo", 227], ["romero", 3], ["salsa-china", 10], ["salsa-alfredo-blanca", 113]] },
];

/** Unidades vendidas 1 jun – 31 jul 2026 (reporte POS). */
export const historicalUnits: Record<string, number> = {
  agua: 277, "cafe-negro": 219, "chivo-del-valle": 141, presidente: 139, "jugo-chinola": 120,
  aguacate: 101, "jugo-limon": 100, habichuelas: 96, cativias: 87, "pechuga-parrilla": 82,
  sancocho: 82, "croquetas-pollo": 80, "almuerzo-ejecutivo": 76, "corona-extra": 75,
  "quesillo-coco": 63, "costillas-bbq": 60, "tostones": 61, "cafe-crema": 61, "presidente-light": 60,
  "jugo-fresa": 69, "bistec-encebollado": 53, "hamburguesa-especial": 51, "frozen-fresa": 51,
  "coca-cola": 73, "sangria-roja": 47, "cafe-leche": 47, perrier: 46, "coca-zero": 44,
  "club-soda": 43, "bolitas-queso": 42, "filete-cerdo-parrilla": 43, "modelo-especial": 40,
  "pasta-alfredo-pollo": 40, "bastoncitos-pollo": 39, conejo: 39, "frozen-limon-menta": 37,
  tamarindo: 37, "gallina-criolla": 36, "pasta-alfredo-camarones": 36, "jugo-cereza": 36,
  "pechuga-salsa-rey": 35, majarete: 35, "aperol-spritz": 35, "filete-res-parrilla": 34,
  "salmon-parrilla": 34, "agua-llevar": 34, cortadito: 33, "churrasco-angus": 32,
  "pina-colada-sin": 32, "zumo-limon": 32, "jugo-pina": 31, "ensalada-constancera": 30,
  "frozen-chinola": 30, "desayuno-dominicano": 29, stella: 28, "morir-chinola": 28,
  "aros-calamar": 27, "pina-colada": 26, expresso: 25, "bruschettas": 25, "san-pellegrino-1l": 25,
  "pasta-4-quesos": 24, helado: 24, "brisa-del-valle": 23, "bizcocho-chocolate": 22,
  sprite: 21, "camarones-ajillo": 21, "morir-naranja": 21, "jugo-naranja": 21,
  "filete-res-queso-azul": 20, bohemia: 20, "papas-fritas": 20, "fresa-leche": 18,
  "frozen-limon": 18, "carne-salada": 17, "filete-cerdo-mostaza": 17, "pasta-tomate": 17,
  "pasta-tocineta": 16, "hamburguesa-pollo": 15, "tabla-mixta": 15, heineken: 15,
  "chocolate-leche": 15, "ensalada-cesar": 14, "canastitas-pollo": 14, "micky-mouse": 14,
  "mojito-coco": 14, "smirnoff-green": 14, "arroz-blanco": 13, "salmon-bosque": 13,
  "mojito-chinola": 13, "carpaccio-res": 12, "salchicha-parrillera": 12, "te-jengibre": 12,
  "desayuno-americano": 11, omelette: 11, "caldo-pollo": 11, "pasta-tomate-camarones": 11,
  "pan-tostado": 11, "asopao-camarones": 11, "camarones-crema": 11, "canastitas-camarones": 11,
  "modelo-negra": 11, negroni: 11, "expresso-martini": 11, cointreau: 11,
  "carpaccio-salmon": 10, "gin-tonic-bombay": 10, "coctel-camarones": 9, "flap-meat": 9,
  ribeye: 9, "tostones-maduro": 9, "corona-zero": 9, "paulaner-dunkel": 9, caipirinha: 9,
  "margarita-fresa": 9, "lambi-vinagreta": 8, "lambi-plato": 8, "pure-cepa": 8,
  "ocean-blue": 8, frappe: 8, "copa-blanco": 8, "margarita-clasica": 8, "morir-limon": 8,
  "caldo-mar": 7, "arroz-mariscos": 7, "pechuga-crema": 7, "vegetales-grill": 7,
  "yuca-frita": 7, "ginger-ale": 7, "paulaner-grande": 7, "mojito-limon": 7,
  "tostada-rustica": 6, "san-pellegrino-250": 6, "lechosa-leche": 6, "gin-tonic-especiado": 6,
  "mojito-fresa": 6, "barcelo-blanco": 6, "el-ligero": 5, casabe: 5, clamato: 5,
  "jugo-limon-menta": 5, "erdinger-dunkel": 5, miller: 5, "gin-tonic-afrutado": 5,
  "sangria-blanca": 5, "tabla-quesos": 4, "chips-yautia": 4, "sandwich-jamon-queso": 4,
  "derretido-queso": 4, "huevos-estrellados": 4, "extra-huevo": 4, "bizcocho-moda": 4,
  "cafe-leche-almendra": 4, tonica: 4, "blue-moon": 4, "paulaner-pequena": 4,
  "smirnoff-ice": 4, "six-eight-nine": 4, "margarita-chinola": 4, mimosa: 4,
  "sangria-rosada": 4, tentacion: 4, "tequila-sunrise": 4, fernet: 4, "glenlivet-12": 4,
  "aceitunas-extra": 4, "emp-hamburguesa": 4,
  "ensalada-capressa": 3, "extra-parmesano": 3, "leche-extra": 3, "red-bull": 3,
  "segura-viudas": 3, "gin-rosado-beefeater": 3, "gin-tonic-beefeater": 3,
  disaronno: 3, "jw-double-black": 3, limoncello: 3, "doble-reserva": 3, "emp-sancocho": 3,
  "emp-flan": 3, croissant: 2, "bizcocho-sorpresa": 2, "quesillo-sorpresa": 2,
  "pure-papa": 2, "tostones-cepa": 2, "expresso-doble": 2, "te-frio": 2,
  "heineken-grande": 2, "jugo-lechosa": 2, "frozen-fresa-limon": 2, "bogle-cab": 2,
  "pra-chardonnay": 2, "protos-verdejo": 2, "cuba-libre": 2, "long-island": 2,
  dewars: 2, "jw-black": 2, "don-julio": 2, "grey-goose": 2, "tia-maria": 2,
  b52: 2, "extra-tocineta": 2, "extra-mozzarella": 2, "salsa-crema": 2,
  "emp-presidente": 2, "emp-sprite": 2, "hue-dominicano": 2, "hue-sandwich": 2,
  "hue-cafe": 2, "emp-soda-amarga": 10,
  "ensalada-mar": 1, "pasta-marinera": 1, "pasta-crema-blanca": 1, "lambi-criolla": 1,
  "camarones-criolla": 1, "croissant-jamon": 1, "guandules-guisados": 1, "moro-guandules": 1,
  "papas-salteadas": 1, "extra-pollo": 1, "extra-salami": 1, "vaso-plastico": 1,
  "emp-bistec": 1, "emp-caldo-pollo": 1, "emp-croquetas": 1, "emp-filete": 1,
  "emp-pechuga": 1, "emp-salchicha": 1, "chocolate-agua": 1, "taza-leche": 1,
  "chinola-fresa-frozen": 1, "jugo-melon": 1, "jugo-fresa-limon": 1, "mezcla-frutas": 1,
  "paulaner-sin": 1, "erdinger-rubia": 1, "heineken-cero": 1, "ilauri-prosecco": 1,
  "bloody-mary": 1, "john-collins": 1, "margarita-deluxe": 1, "vodka-sol": 1,
  "old-parr": 1, "fernet-menta": 1, bombay: 1, ginebra: 1, "brugal-1888": 1,
  descorche: 1, "descorche-chivas": 1, "extra-leche-almendra": 1, "vaso-hielo": 1,
  "vela-cumple": 1, "hue-agua": 1, "hue-chinola": 1, "hue-limon": 1,
  "emp-agua": 71, "emp-coca": 36,
};
