export type Unidad = "G" | "ML" | "UD";

export const categories = [
  { id: "entradas", nombre: "Entradas", tipo: "COMIDA" as const, esInterna: false, orden: 1 },
  { id: "especialidades", nombre: "Especialidades de la Montaña", tipo: "COMIDA" as const, esInterna: false, orden: 2 },
  { id: "cortes", nombre: "Cortes y Carnes", tipo: "COMIDA" as const, esInterna: false, orden: 3 },
  { id: "ensaladas", nombre: "Ensaladas", tipo: "COMIDA" as const, esInterna: false, orden: 4 },
  { id: "caldos", nombre: "Caldos", tipo: "COMIDA" as const, esInterna: false, orden: 5 },
  { id: "picaderas", nombre: "Picaderas", tipo: "COMIDA" as const, esInterna: false, orden: 6 },
  { id: "pastas", nombre: "Pastas", tipo: "COMIDA" as const, esInterna: false, orden: 7 },
  { id: "arroces", nombre: "Arroces", tipo: "COMIDA" as const, esInterna: false, orden: 8 },
  { id: "pescados", nombre: "Pescados y Mariscos", tipo: "COMIDA" as const, esInterna: false, orden: 9 },
  { id: "postres", nombre: "Postres", tipo: "COMIDA" as const, esInterna: false, orden: 10 },
  { id: "guarniciones", nombre: "Guarniciones", tipo: "COMIDA" as const, esInterna: false, orden: 11 },
  { id: "desayunos", nombre: "Desayunos", tipo: "COMIDA" as const, esInterna: false, orden: 12 },
  { id: "jugos", nombre: "Jugos Naturales", tipo: "BEBIDA" as const, esInterna: false, orden: 13 },
  { id: "cafes", nombre: "Cafés y Té", tipo: "BEBIDA" as const, esInterna: false, orden: 14 },
  { id: "cervezas", nombre: "Cervezas", tipo: "BEBIDA" as const, esInterna: false, orden: 15 },
  { id: "cocteles", nombre: "Cócteles", tipo: "BEBIDA" as const, esInterna: false, orden: 16 },
  { id: "refrescos", nombre: "Agua y Refrescos", tipo: "BEBIDA" as const, esInterna: false, orden: 17 },
  { id: "ninos", nombre: "Para Niños", tipo: "BEBIDA" as const, esInterna: false, orden: 18 },
  { id: "vinos", nombre: "Vinos", tipo: "BEBIDA" as const, esInterna: false, orden: 19 },
  { id: "licores", nombre: "Licores y Digestivos", tipo: "BEBIDA" as const, esInterna: false, orden: 20 },
  { id: "emp-comida", nombre: "Comida Empleados", tipo: "COMIDA" as const, esInterna: true, orden: 90 },
  { id: "emp-bebida", nombre: "Consumo Empleados", tipo: "BEBIDA" as const, esInterna: true, orden: 91 },
  { id: "huespedes", nombre: "Huéspedes", tipo: "COMIDA" as const, esInterna: true, orden: 92 },
  { id: "extras", nombre: "Extras Varios", tipo: "COMIDA" as const, esInterna: true, orden: 93 },
];

type DishSeed = {
  id: string;
  nombre: string;
  categoryId: string;
  precio?: number | null;
  descripcion?: string;
  destacado?: boolean;
  incluyeGuarnicion?: boolean;
};

export const dishes: DishSeed[] = [
  { id: "aros-calamar", nombre: "Aros de Calamar", categoryId: "entradas", precio: 495 },
  { id: "croquetas-pollo", nombre: "Croquetas de Pollo", categoryId: "entradas", precio: 425 },
  { id: "bolitas-queso", nombre: "Bolitas de Queso", categoryId: "entradas", precio: 420 },
  { id: "bruschettas", nombre: "Bruschettas de Tomate y Parmesano", categoryId: "entradas", precio: 395 },
  { id: "cativias", nombre: "Cativías (3 por servicio)", categoryId: "entradas", precio: 365, descripcion: "Masa de yuca rellena de queso" },
  { id: "aceitunas-rellenas", nombre: "Aceitunas Rellenas", categoryId: "entradas", precio: 300 },
  { id: "carpaccio-salmon", nombre: "Carpaccio de Salmón", categoryId: "entradas", precio: 745 },
  { id: "carpaccio-res", nombre: "Carpaccio de Res", categoryId: "entradas", precio: 765 },
  { id: "lambi-vinagreta", nombre: "Lambí a la Vinagreta", categoryId: "entradas", precio: 695 },
  { id: "coctel-camarones", nombre: "Cóctel de Camarones", categoryId: "entradas", precio: 850 },
  { id: "tabla-quesos", nombre: "Tabla de Quesos e Ibéricos", categoryId: "entradas", precio: 1550, descripcion: "Manchego, ibérico curado, queso de cabra, jamón serrano, aceitunas, pan y mermelada" },

  { id: "chivo-del-valle", nombre: "Chivo del Valle", categoryId: "especialidades", precio: 960, descripcion: "Cocido en salsa de la casa. Guarnición de preferencia incluida.", destacado: true, incluyeGuarnicion: true },
  { id: "conejo", nombre: "Conejo", categoryId: "especialidades", precio: 990, descripcion: "A la parrilla, toque de romero. Guarnición incluida.", destacado: true, incluyeGuarnicion: true },
  { id: "gallina-criolla", nombre: "Gallina Criolla", categoryId: "especialidades", precio: 895, descripcion: "Cocida en salsa de la casa. Guarnición incluida.", destacado: true, incluyeGuarnicion: true },

  { id: "pechuga-parrilla", nombre: "Pechuga a la Parrilla", categoryId: "cortes", precio: 650, incluyeGuarnicion: true },
  { id: "pechuga-salsa-rey", nombre: "Pechuga a la Parrilla terminada en Salsa del Rey", categoryId: "cortes", precio: 770, incluyeGuarnicion: true },
  { id: "filete-cerdo-parrilla", nombre: "Filete de Cerdo a la Parrilla", categoryId: "cortes", precio: 760, incluyeGuarnicion: true },
  { id: "filete-cerdo-mostaza", nombre: "Filete de Cerdo en Salsa de Mostaza y Especias", categoryId: "cortes", precio: 860, incluyeGuarnicion: true },
  { id: "costillas-bbq", nombre: "Costillas de Cerdo terminadas con Salsa BBQ de la Casa", categoryId: "cortes", precio: 895, destacado: true, incluyeGuarnicion: true },
  { id: "bistec-encebollado", nombre: "Bistec Encebollado con Toque de Vino Tinto", categoryId: "cortes", precio: 790, destacado: true, incluyeGuarnicion: true },
  { id: "filete-res-parrilla", nombre: "Filete de Res a la Parrilla", categoryId: "cortes", precio: 900, incluyeGuarnicion: true },
  { id: "filete-res-queso-azul", nombre: "Filete de Res terminado en Salsa de Queso Azul", categoryId: "cortes", precio: 990, incluyeGuarnicion: true },
  { id: "churrasco-angus", nombre: "Churrasco Angus a la Parrilla (8 oz)", categoryId: "cortes", precio: 1990, incluyeGuarnicion: true },
  { id: "flap-meat", nombre: "Flap Meat Angus a la Parrilla (8 oz)", categoryId: "cortes", precio: 1895, incluyeGuarnicion: true },
  { id: "ribeye", nombre: "Ribeye a la Parrilla en Salsa de Finas Hierbas (8 oz)", categoryId: "cortes", precio: 2295, incluyeGuarnicion: true },
  { id: "pechuga-crema", nombre: "Pechuga a la Crema", categoryId: "cortes", precio: null, incluyeGuarnicion: true },

  { id: "ensalada-constancera", nombre: "Ensalada Constancera", categoryId: "ensaladas", precio: 350, descripcion: "Lechuga, tomate, pepino y zanahoria" },
  { id: "ensalada-cesar", nombre: "Ensalada César con Pollo", categoryId: "ensaladas", precio: 600 },
  { id: "ensalada-capressa", nombre: "Ensalada Capressa", categoryId: "ensaladas", precio: 500 },
  { id: "ensalada-mar", nombre: "Ensalada del Mar", categoryId: "ensaladas", precio: 1095, descripcion: "Mix de mariscos de temporada" },

  { id: "sancocho", nombre: "Sancocho Clásico", categoryId: "caldos", precio: 795, descripcion: "Tres carnes y mix de tubérculos, con arroz blanco", destacado: true },
  { id: "caldo-pollo", nombre: "Caldo de Pollo y Vegetales", categoryId: "caldos", precio: 650 },
  { id: "caldo-mar", nombre: "Caldo del Mar", categoryId: "caldos", precio: 1125, descripcion: "Mariscos y trocitos de salmón, con tostones o arroz" },

  { id: "bastoncitos-pollo", nombre: "Bastoncitos de Pollo", categoryId: "picaderas", precio: 550 },
  { id: "canastitas-pollo", nombre: "Canastitas de Pollo", categoryId: "picaderas", precio: 650, descripcion: "A la parrilla o a la crema" },
  { id: "canastitas-camarones", nombre: "Canastitas de Camarones", categoryId: "picaderas", precio: 885, descripcion: "Parrilla, crema o ajillo" },
  { id: "carne-salada", nombre: "Carne Salada", categoryId: "picaderas", precio: 625 },
  { id: "salchicha-parrillera", nombre: "Salchicha Parrillera", categoryId: "picaderas", precio: 500 },
  { id: "hamburguesa-especial", nombre: "Hamburguesa Especial con Bacon", categoryId: "picaderas", precio: 695, descripcion: "Res, queso, vegetales, bacon y papas fritas" },
  { id: "hamburguesa-pollo", nombre: "Hamburguesa de Pollo", categoryId: "picaderas", precio: 645, descripcion: "Pechuga a la parrilla y papas fritas" },
  { id: "tabla-mixta", nombre: "Tabla Mixta VDV para 4 Personas", categoryId: "picaderas", precio: 2995, descripcion: "Cerdo, pollo, res y salchicha" },

  { id: "pasta-alfredo-pollo", nombre: "Pasta Alfredo con Pollo", categoryId: "pastas", precio: 650, descripcion: "Espagueti, penne o linguini" },
  { id: "pasta-alfredo-camarones", nombre: "Pasta Alfredo con Camarones", categoryId: "pastas", precio: 995 },
  { id: "pasta-tomate", nombre: "Pasta de Tomates Frescos y Toque de Parmesano", categoryId: "pastas", precio: 500 },
  { id: "pasta-tomate-camarones", nombre: "Pasta de Tomates Frescos con Camarones", categoryId: "pastas", precio: 975 },
  { id: "pasta-4-quesos", nombre: "Pasta 4 Quesos", categoryId: "pastas", precio: 595 },
  { id: "pasta-tocineta", nombre: "Pasta con Tocineta y Parmesano", categoryId: "pastas", precio: 675 },
  { id: "pasta-marinera", nombre: "Pasta a la Marinera", categoryId: "pastas", precio: 1195, descripcion: "Camarones, salmón, calamar, mejillones, salsa de tomates frescos" },
  { id: "pasta-crema-blanca", nombre: "Pasta en Crema Blanca", categoryId: "pastas", precio: null },
  { id: "pan-tostado", nombre: "Pan Tostado", categoryId: "pastas", precio: null },

  { id: "arroz-mariscos", nombre: "Arroz con Mariscos Mixtos", categoryId: "arroces", precio: 1095, descripcion: "Acompañado de ensalada constancera" },
  { id: "asopao-camarones", nombre: "Asopao de Camarones", categoryId: "arroces", precio: 960 },
  { id: "asopao-mariscos", nombre: "Asopao de Mariscos Mixtos", categoryId: "arroces", precio: 1050 },

  { id: "salmon-parrilla", nombre: "Salmón Fresco a la Parrilla", categoryId: "pescados", precio: 1075, incluyeGuarnicion: true },
  { id: "salmon-bosque", nombre: "Salmón a la Parrilla terminado en Salsa del Bosque", categoryId: "pescados", precio: 1195, incluyeGuarnicion: true },
  { id: "camarones-almendras", nombre: "Camarones Rostizados en Salsa de Almendras", categoryId: "pescados", precio: 995, incluyeGuarnicion: true },
  { id: "camarones-ajillo", nombre: "Camarones al Ajillo", categoryId: "pescados", precio: 960, incluyeGuarnicion: true },
  { id: "camarones-crema", nombre: "Camarones terminados en Crema Blanca", categoryId: "pescados", precio: 960, incluyeGuarnicion: true },
  { id: "lambi-plato", nombre: "Lambí (vinagreta o criolla)", categoryId: "pescados", precio: 950, incluyeGuarnicion: true },
  { id: "lambi-criolla", nombre: "Lambí a la Criolla", categoryId: "pescados", precio: 950, incluyeGuarnicion: true },
  { id: "camarones-criolla", nombre: "Camarones a la Criolla", categoryId: "pescados", precio: null, incluyeGuarnicion: true },
  { id: "langostinos-bandera", nombre: "Langostinos a la Bandera", categoryId: "pescados", precio: 1550, descripcion: "Crema blanca, curry y especias, o al grill", incluyeGuarnicion: true },

  { id: "dulce-coco", nombre: "Dulce de Coco Tierno", categoryId: "postres", precio: 280 },
  { id: "majarete", nombre: "Majarete", categoryId: "postres", precio: 280 },
  { id: "quesillo-coco", nombre: "Quesillo de Coco", categoryId: "postres", precio: 260 },
  { id: "bizcocho-chocolate", nombre: "Bizcocho de Chocolate", categoryId: "postres", precio: 300 },
  { id: "helado", nombre: "Helado", categoryId: "postres", precio: 260 },
  { id: "bizcocho-moda", nombre: "Bizcocho a la Moda", categoryId: "postres", precio: null },
  { id: "bizcocho-sorpresa", nombre: "Bizcocho Sorpresa", categoryId: "postres", precio: null },
  { id: "quesillo-sorpresa", nombre: "Quesillo Sorpresa", categoryId: "postres", precio: null },

  { id: "tostones", nombre: "Tostones", categoryId: "guarniciones", precio: null },
  { id: "casabe", nombre: "Casabe Tostado", categoryId: "guarniciones", precio: null },
  { id: "papas-fritas", nombre: "Papas Fritas", categoryId: "guarniciones", precio: null },
  { id: "papas-salteadas", nombre: "Papas Salteadas", categoryId: "guarniciones", precio: null },
  { id: "aguacate", nombre: "Aguacate", categoryId: "guarniciones", precio: null },
  { id: "vegetales-grill", nombre: "Vegetales al Grill", categoryId: "guarniciones", precio: null },
  { id: "yuca-frita", nombre: "Yuca Frita", categoryId: "guarniciones", precio: null },
  { id: "tostones-maduro", nombre: "Tostones de Maduro", categoryId: "guarniciones", precio: null },
  { id: "pure-papa", nombre: "Puré de Papas", categoryId: "guarniciones", precio: null },
  { id: "chips-yautia", nombre: "Chips de Yautía", categoryId: "guarniciones", precio: null },
  { id: "pure-cepa", nombre: "Puré de Cepa de Apio", categoryId: "guarniciones", precio: null },
  { id: "moro-guandules", nombre: "Moro de Guandules", categoryId: "guarniciones", precio: null },
  { id: "arroz-blanco", nombre: "Arroz Blanco", categoryId: "guarniciones", precio: null },
  { id: "habichuelas", nombre: "Habichuelas Guisadas", categoryId: "guarniciones", precio: null },
  { id: "guandules-guisados", nombre: "Guandules Guisados", categoryId: "guarniciones", precio: null },
  { id: "tostones-cepa", nombre: "Tostones de Cepa de Apio", categoryId: "guarniciones", precio: null },

  { id: "desayuno-dominicano", nombre: "Desayuno Clásico Dominicano", categoryId: "desayunos", precio: null },
  { id: "desayuno-americano", nombre: "Desayuno Americano", categoryId: "desayunos", precio: null },
  { id: "omelette", nombre: "Omelette con Pan Tostado", categoryId: "desayunos", precio: null },
  { id: "tostada-rustica", nombre: "Tostada Rústica de la Casa", categoryId: "desayunos", precio: null },
  { id: "el-ligero", nombre: "El Ligero", categoryId: "desayunos", precio: null },
  { id: "sandwich-jamon-queso", nombre: "Sándwich Jamón y Queso Mozzarella", categoryId: "desayunos", precio: null },
  { id: "derretido-queso", nombre: "Derretido de Queso", categoryId: "desayunos", precio: null },
  { id: "croissant", nombre: "Croissant Clásico", categoryId: "desayunos", precio: null },
  { id: "huevos-estrellados", nombre: "Huevos Estrellados", categoryId: "desayunos", precio: null },
  { id: "croissant-jamon", nombre: "Croissant Jamón y Queso", categoryId: "desayunos", precio: null },

  { id: "jugo-chinola", nombre: "Jugo de Chinola", categoryId: "jugos" },
  { id: "jugo-limon", nombre: "Jugo de Limón", categoryId: "jugos" },
  { id: "jugo-fresa", nombre: "Jugo de Fresa", categoryId: "jugos" },
  { id: "jugo-cereza", nombre: "Jugo de Cereza", categoryId: "jugos" },
  { id: "jugo-pina", nombre: "Jugo de Piña", categoryId: "jugos" },
  { id: "jugo-naranja", nombre: "Jugo de Naranja", categoryId: "jugos" },
  { id: "tamarindo", nombre: "Tamarindo", categoryId: "jugos" },
  { id: "lechosa-leche", nombre: "Lechosa con Leche", categoryId: "jugos" },
  { id: "jugo-lechosa", nombre: "Jugo de Lechosa", categoryId: "jugos" },
  { id: "morir-chinola", nombre: "Morir Soñando de Chinola", categoryId: "jugos" },
  { id: "morir-naranja", nombre: "Morir Soñando de Naranja", categoryId: "jugos" },
  { id: "morir-limon", nombre: "Morir Soñando de Limón", categoryId: "jugos" },
  { id: "frozen-fresa", nombre: "Frozen de Fresa", categoryId: "jugos" },
  { id: "frozen-chinola", nombre: "Frozen de Chinola", categoryId: "jugos" },
  { id: "frozen-limon", nombre: "Frozen de Limón", categoryId: "jugos" },
  { id: "frozen-limon-menta", nombre: "Frozen de Limón con Menta", categoryId: "jugos" },
  { id: "fresa-leche", nombre: "Fresa con Leche", categoryId: "jugos" },
  { id: "jugo-limon-menta", nombre: "Jugo Limón Menta", categoryId: "jugos" },
  { id: "frozen-fresa-limon", nombre: "Frozen Fresa con Limón", categoryId: "jugos" },
  { id: "chinola-fresa-frozen", nombre: "Chinola con Fresa Frozen", categoryId: "jugos" },
  { id: "jugo-melon", nombre: "Jugo de Melón", categoryId: "jugos" },
  { id: "jugo-fresa-limon", nombre: "Jugo Fresa Limón", categoryId: "jugos" },
  { id: "mezcla-frutas", nombre: "Mezcla Frutas", categoryId: "jugos" },

  { id: "cafe-negro", nombre: "Café Negro", categoryId: "cafes" },
  { id: "cafe-crema", nombre: "Café con Crema", categoryId: "cafes" },
  { id: "cafe-leche", nombre: "Café con Leche", categoryId: "cafes" },
  { id: "cortadito", nombre: "Cortadito", categoryId: "cafes" },
  { id: "expresso", nombre: "Expresso", categoryId: "cafes" },
  { id: "expresso-doble", nombre: "Expresso Doble", categoryId: "cafes" },
  { id: "frappe", nombre: "Frappe", categoryId: "cafes" },
  { id: "chocolate-leche", nombre: "Chocolate con Leche", categoryId: "cafes" },
  { id: "te-jengibre", nombre: "Té de la Casa con Jengibre", categoryId: "cafes" },
  { id: "te-frio", nombre: "Té Frío", categoryId: "cafes" },
  { id: "cafe-leche-almendra", nombre: "Café con Leche Almendra", categoryId: "cafes" },
  { id: "leche-extra", nombre: "Leche Extra", categoryId: "cafes" },
  { id: "chocolate-agua", nombre: "Chocolate de Agua", categoryId: "cafes" },
  { id: "taza-leche", nombre: "Taza de Leche Entera", categoryId: "cafes" },

  { id: "presidente", nombre: "Presidente Normal", categoryId: "cervezas" },
  { id: "presidente-light", nombre: "Presidente Light", categoryId: "cervezas" },
  { id: "corona-extra", nombre: "Corona Extra", categoryId: "cervezas" },
  { id: "corona-zero", nombre: "Corona Zero", categoryId: "cervezas" },
  { id: "modelo-especial", nombre: "Modelo Especial Rubia", categoryId: "cervezas" },
  { id: "modelo-negra", nombre: "Modelo Negra", categoryId: "cervezas" },
  { id: "bohemia", nombre: "Bohemia", categoryId: "cervezas" },
  { id: "heineken", nombre: "Heineken", categoryId: "cervezas" },
  { id: "heineken-grande", nombre: "Heineken Grande", categoryId: "cervezas" },
  { id: "heineken-cero", nombre: "Heineken Cero", categoryId: "cervezas" },
  { id: "stella", nombre: "Stella Artois", categoryId: "cervezas" },
  { id: "paulaner-dunkel", nombre: "Paulaner Negra Dunkel", categoryId: "cervezas" },
  { id: "paulaner-grande", nombre: "Paulaner Grande Rubia", categoryId: "cervezas" },
  { id: "paulaner-pequena", nombre: "Paulaner Pequeña Rubia", categoryId: "cervezas" },
  { id: "paulaner-sin", nombre: "Paulaner sin Alcohol", categoryId: "cervezas" },
  { id: "blue-moon", nombre: "Blue Moon Belgian", categoryId: "cervezas" },
  { id: "miller", nombre: "Miller Draft", categoryId: "cervezas" },
  { id: "smirnoff-ice", nombre: "Smirnoff Ice", categoryId: "cervezas" },
  { id: "smirnoff-green", nombre: "Smirnoff Green Apple", categoryId: "cervezas" },
  { id: "erdinger-dunkel", nombre: "Erdinger Dunkel", categoryId: "cervezas" },
  { id: "erdinger-rubia", nombre: "Erdinger Rubia", categoryId: "cervezas" },

  { id: "sangria-roja", nombre: "Sangría Roja", categoryId: "cocteles" },
  { id: "aperol-spritz", nombre: "Aperol Spritz", categoryId: "cocteles" },
  { id: "pina-colada-sin", nombre: "Piña Colada sin Alcohol", categoryId: "cocteles" },
  { id: "pina-colada", nombre: "Piña Colada con Alcohol", categoryId: "cocteles" },
  { id: "brisa-del-valle", nombre: "Brisa del Valle", categoryId: "cocteles" },
  { id: "mojito-coco", nombre: "Mojito Coco", categoryId: "cocteles" },
  { id: "mojito-chinola", nombre: "Mojito Chinola", categoryId: "cocteles" },
  { id: "mojito-fresa", nombre: "Mojito Fresa", categoryId: "cocteles" },
  { id: "mojito-limon", nombre: "Mojito Limón", categoryId: "cocteles" },
  { id: "negroni", nombre: "Negroni", categoryId: "cocteles" },
  { id: "expresso-martini", nombre: "Expresso Martini", categoryId: "cocteles" },
  { id: "gin-tonic-bombay", nombre: "Gin Tonic Bombay", categoryId: "cocteles" },
  { id: "caipirinha", nombre: "Caipirinha", categoryId: "cocteles" },
  { id: "margarita-fresa", nombre: "Margarita Frozen Fresa", categoryId: "cocteles" },
  { id: "margarita-clasica", nombre: "Margarita Clásica", categoryId: "cocteles" },
  { id: "gin-tonic-especiado", nombre: "Gin Tonic Especiado", categoryId: "cocteles" },
  { id: "gin-tonic-afrutado", nombre: "Gin Tonic Afrutado", categoryId: "cocteles" },
  { id: "sangria-blanca", nombre: "Sangría Blanca", categoryId: "cocteles" },
  { id: "margarita-chinola", nombre: "Margarita Frozen Chinola", categoryId: "cocteles" },
  { id: "mimosa", nombre: "Mimosa", categoryId: "cocteles" },
  { id: "sangria-rosada", nombre: "Sangría Rosada", categoryId: "cocteles" },
  { id: "tentacion", nombre: "Tentación", categoryId: "cocteles" },
  { id: "tequila-sunrise", nombre: "Tequila Sunrise", categoryId: "cocteles" },
  { id: "gin-rosado-beefeater", nombre: "Gin Rosado Beefeater", categoryId: "cocteles" },
  { id: "gin-tonic-beefeater", nombre: "Gin Tonic Beefeater Clásico", categoryId: "cocteles" },
  { id: "cuba-libre", nombre: "Cuba Libre", categoryId: "cocteles" },
  { id: "bloody-mary", nombre: "Bloody Mary", categoryId: "cocteles" },
  { id: "long-island", nombre: "Long Island", categoryId: "cocteles" },
  { id: "john-collins", nombre: "John Collins", categoryId: "cocteles" },
  { id: "margarita-deluxe", nombre: "Margarita Deluxe", categoryId: "cocteles" },
  { id: "vodka-sol", nombre: "Vodka y Sol", categoryId: "cocteles" },

  { id: "agua", nombre: "Agua", categoryId: "refrescos" },
  { id: "coca-cola", nombre: "Coca Cola", categoryId: "refrescos" },
  { id: "coca-zero", nombre: "Coca Cola Zero", categoryId: "refrescos" },
  { id: "sprite", nombre: "Sprite", categoryId: "refrescos" },
  { id: "club-soda", nombre: "Club Soda", categoryId: "refrescos" },
  { id: "ginger-ale", nombre: "Ginger Ale", categoryId: "refrescos" },
  { id: "tonica", nombre: "Tónica", categoryId: "refrescos" },
  { id: "perrier", nombre: "Perrier", categoryId: "refrescos" },
  { id: "san-pellegrino-1l", nombre: "San Pellegrino 1L", categoryId: "refrescos" },
  { id: "san-pellegrino-250", nombre: "San Pellegrino 250ml", categoryId: "refrescos" },
  { id: "red-bull", nombre: "Red Bull", categoryId: "refrescos" },
  { id: "clamato", nombre: "Clamato", categoryId: "refrescos" },

  { id: "micky-mouse", nombre: "Micky Mouse", categoryId: "ninos" },
  { id: "ocean-blue", nombre: "Ocean Blue", categoryId: "ninos" },

  { id: "copa-tinto", nombre: "Copa Vino Tinto", categoryId: "vinos" },
  { id: "copa-blanco", nombre: "Copa Vino Blanco", categoryId: "vinos" },
  { id: "six-eight-nine", nombre: "Six Eight Nine Red Blend", categoryId: "vinos" },
  { id: "segura-viudas", nombre: "Segura Viudas Brut Reserva", categoryId: "vinos" },
  { id: "bogle-cab", nombre: "Bogle Cabernet Sauvignon", categoryId: "vinos" },
  { id: "pra-chardonnay", nombre: "Pra Vinera Reserve Chardonnay", categoryId: "vinos" },
  { id: "protos-verdejo", nombre: "Protos Verdejo", categoryId: "vinos" },
  { id: "ilauri-prosecco", nombre: "Ilauri Prosecco", categoryId: "vinos" },

  { id: "cointreau", nombre: "Cointreau", categoryId: "licores" },
  { id: "barcelo-blanco", nombre: "Barceló Blanco", categoryId: "licores" },
  { id: "fernet", nombre: "Fernet Branca", categoryId: "licores" },
  { id: "glenlivet-12", nombre: "Glenlivet 12", categoryId: "licores" },
  { id: "disaronno", nombre: "Disaronno", categoryId: "licores" },
  { id: "jw-double-black", nombre: "J.W. Double Black", categoryId: "licores" },
  { id: "limoncello", nombre: "Limoncello", categoryId: "licores" },
  { id: "doble-reserva", nombre: "Doble Reserva", categoryId: "licores" },
  { id: "dewars", nombre: "Dewars", categoryId: "licores" },
  { id: "jw-black", nombre: "J.W. Black", categoryId: "licores" },
  { id: "don-julio", nombre: "Don Julio Reposado", categoryId: "licores" },
  { id: "grey-goose", nombre: "Grey Goose", categoryId: "licores" },
  { id: "tia-maria", nombre: "Tía María", categoryId: "licores" },
  { id: "old-parr", nombre: "Old Parr", categoryId: "licores" },
  { id: "fernet-menta", nombre: "Fernet Menta", categoryId: "licores" },
  { id: "bombay", nombre: "Bombay", categoryId: "licores" },
  { id: "ginebra", nombre: "Ginebra", categoryId: "licores" },
  { id: "brugal-1888", nombre: "Brugal 1888 (botella)", categoryId: "licores" },

  { id: "emp-hamburguesa", nombre: "Hamburguesa Especial (empleado)", categoryId: "emp-comida" },
  { id: "emp-sancocho", nombre: "Sancocho (empleado)", categoryId: "emp-comida" },
  { id: "emp-bistec", nombre: "Bistec Encebollado (empleado)", categoryId: "emp-comida" },
  { id: "emp-caldo-pollo", nombre: "Caldo de Pollo (empleado)", categoryId: "emp-comida" },
  { id: "emp-croquetas", nombre: "Croquetas de Pollo (empleado)", categoryId: "emp-comida" },
  { id: "emp-filete", nombre: "Filete a la Parrilla (empleado)", categoryId: "emp-comida" },
  { id: "emp-pechuga", nombre: "Pechuga a la Parrilla (empleado)", categoryId: "emp-comida" },
  { id: "emp-salchicha", nombre: "Salchicha (empleado)", categoryId: "emp-comida" },
  { id: "emp-agua", nombre: "Agua (empleado)", categoryId: "emp-bebida" },
  { id: "emp-coca", nombre: "Coca Cola (empleado)", categoryId: "emp-bebida" },
  { id: "emp-soda-amarga", nombre: "Soda amarga (empleado)", categoryId: "emp-bebida" },
  { id: "emp-flan", nombre: "Flan (empleado)", categoryId: "emp-comida" },
  { id: "emp-presidente", nombre: "Presidente (empleado)", categoryId: "emp-bebida" },
  { id: "emp-sprite", nombre: "Sprite (empleado)", categoryId: "emp-bebida" },
  { id: "hue-dominicano", nombre: "Desayuno Dominicano (huésped)", categoryId: "huespedes" },
  { id: "hue-sandwich", nombre: "Sándwich Jamón y Queso (huésped)", categoryId: "huespedes" },
  { id: "hue-cafe", nombre: "Café Negro (huésped)", categoryId: "huespedes" },
  { id: "hue-agua", nombre: "Agua (huésped)", categoryId: "huespedes" },
  { id: "hue-chinola", nombre: "Jugo de Chinola (huésped)", categoryId: "huespedes" },
  { id: "hue-limon", nombre: "Jugo de Limón (huésped)", categoryId: "huespedes" },
  { id: "almuerzo-ejecutivo", nombre: "Almuerzo Ejecutivo", categoryId: "extras" },
  { id: "agua-llevar", nombre: "Agua para llevar", categoryId: "extras" },
  { id: "zumo-limon", nombre: "Zumo de limón", categoryId: "extras" },
  { id: "extra-huevo", nombre: "Huevo Extra", categoryId: "extras" },
  { id: "extra-parmesano", nombre: "Parmesano Extra", categoryId: "extras" },
  { id: "extra-tocineta", nombre: "Extra Tocineta", categoryId: "extras" },
  { id: "extra-mozzarella", nombre: "Queso Mozzarella Extra", categoryId: "extras" },
  { id: "extra-pollo", nombre: "Extra Pollo", categoryId: "extras" },
  { id: "extra-salami", nombre: "Salami Extra", categoryId: "extras" },
  { id: "salsa-crema", nombre: "Salsa a la Crema", categoryId: "extras" },
  { id: "vaso-plastico", nombre: "Vaso Plástico", categoryId: "extras" },
  { id: "b52", nombre: "B-52", categoryId: "extras" },
  { id: "descorche", nombre: "Descorche", categoryId: "extras" },
  { id: "descorche-chivas", nombre: "Descorche de Chivas", categoryId: "extras" },
  { id: "extra-leche-almendra", nombre: "Extra leche almendra", categoryId: "extras" },
  { id: "vaso-hielo", nombre: "Vaso con hielo", categoryId: "extras" },
  { id: "vela-cumple", nombre: "Vela de cumpleaños", categoryId: "extras" },
  { id: "aceitunas-extra", nombre: "Aceitunas rellenas (extra)", categoryId: "extras" },
];

export const ingredients: { id: string; nombre: string; unidad: Unidad; minimo: number }[] = [
  { id: "chivo", nombre: "Carne de chivo", unidad: "G", minimo: 2000 },
  { id: "conejo", nombre: "Carne de conejo", unidad: "G", minimo: 1500 },
  { id: "gallina", nombre: "Gallina criolla", unidad: "G", minimo: 1500 },
  { id: "bistec-res", nombre: "Bistec de res", unidad: "G", minimo: 2000 },
  { id: "filete-res", nombre: "Filete de res", unidad: "G", minimo: 2000 },
  { id: "churrasco", nombre: "Churrasco angus", unidad: "G", minimo: 1500 },
  { id: "flap-meat", nombre: "Flap meat angus", unidad: "G", minimo: 1000 },
  { id: "ribeye", nombre: "Ribeye", unidad: "G", minimo: 1000 },
  { id: "filete-cerdo", nombre: "Filete de cerdo", unidad: "G", minimo: 2000 },
  { id: "costilla-cerdo", nombre: "Costilla de cerdo", unidad: "G", minimo: 2000 },
  { id: "pechuga", nombre: "Pechuga de pollo", unidad: "G", minimo: 3000 },
  { id: "pollo", nombre: "Pollo (desmenuzado/caldo)", unidad: "G", minimo: 1000 },
  { id: "carne-molida", nombre: "Carne molida de res", unidad: "G", minimo: 1500 },
  { id: "carne-salada", nombre: "Carne salada", unidad: "G", minimo: 1000 },
  { id: "tocineta", nombre: "Tocineta / bacon", unidad: "G", minimo: 500 },
  { id: "salchicha", nombre: "Salchicha parrillera", unidad: "G", minimo: 1000 },
  { id: "jamon-serrano", nombre: "Jamón serrano", unidad: "G", minimo: 300 },
  { id: "salami", nombre: "Salami", unidad: "G", minimo: 300 },
  { id: "camarones", nombre: "Camarones", unidad: "G", minimo: 2000 },
  { id: "calamar", nombre: "Calamar (anillas)", unidad: "G", minimo: 1000 },
  { id: "mejillones", nombre: "Mejillones", unidad: "G", minimo: 500 },
  { id: "lambi", nombre: "Lambí", unidad: "G", minimo: 1000 },
  { id: "langostinos", nombre: "Langostinos", unidad: "G", minimo: 800 },
  { id: "salmon", nombre: "Salmón fresco", unidad: "G", minimo: 1500 },
  { id: "mix-mariscos", nombre: "Mix de mariscos", unidad: "G", minimo: 1000 },
  { id: "mozzarella", nombre: "Queso mozzarella", unidad: "G", minimo: 1000 },
  { id: "parmesano", nombre: "Parmesano", unidad: "G", minimo: 500 },
  { id: "queso-azul", nombre: "Queso azul", unidad: "G", minimo: 300 },
  { id: "gouda", nombre: "Queso gouda", unidad: "G", minimo: 300 },
  { id: "manchego", nombre: "Queso manchego", unidad: "G", minimo: 300 },
  { id: "iberico", nombre: "Queso ibérico curado", unidad: "G", minimo: 300 },
  { id: "queso-cabra", nombre: "Queso de cabra", unidad: "G", minimo: 300 },
  { id: "queso-crema", nombre: "Queso crema", unidad: "G", minimo: 500 },
  { id: "queso-cativia", nombre: "Queso para cativía", unidad: "G", minimo: 500 },
  { id: "crema-leche", nombre: "Crema de leche", unidad: "ML", minimo: 2000 },
  { id: "leche", nombre: "Leche entera", unidad: "ML", minimo: 2000 },
  { id: "leche-almendra", nombre: "Leche de almendra", unidad: "ML", minimo: 500 },
  { id: "mantequilla", nombre: "Mantequilla", unidad: "G", minimo: 500 },
  { id: "helado-vainilla", nombre: "Helado de vainilla", unidad: "ML", minimo: 2000 },
  { id: "lechuga", nombre: "Lechuga", unidad: "G", minimo: 1000 },
  { id: "tomate", nombre: "Tomate", unidad: "G", minimo: 2000 },
  { id: "pepino", nombre: "Pepino", unidad: "G", minimo: 500 },
  { id: "zanahoria", nombre: "Zanahoria", unidad: "G", minimo: 500 },
  { id: "cebolla", nombre: "Cebolla", unidad: "G", minimo: 2000 },
  { id: "pimiento", nombre: "Pimiento", unidad: "G", minimo: 500 },
  { id: "ajo", nombre: "Ajo", unidad: "G", minimo: 300 },
  { id: "apio", nombre: "Apio", unidad: "G", minimo: 300 },
  { id: "auyama", nombre: "Auyama", unidad: "G", minimo: 1000 },
  { id: "papa", nombre: "Papa", unidad: "G", minimo: 3000 },
  { id: "yuca", nombre: "Yuca", unidad: "G", minimo: 2000 },
  { id: "name", nombre: "Ñame", unidad: "G", minimo: 800 },
  { id: "platano-verde", nombre: "Plátano verde", unidad: "UD", minimo: 30 },
  { id: "platano-maduro", nombre: "Plátano maduro", unidad: "UD", minimo: 15 },
  { id: "yautia", nombre: "Yautía", unidad: "G", minimo: 1000 },
  { id: "cepa-apio", nombre: "Cepa de apio", unidad: "G", minimo: 800 },
  { id: "aguacate", nombre: "Aguacate", unidad: "UD", minimo: 15 },
  { id: "champinones", nombre: "Champiñones", unidad: "G", minimo: 500 },
  { id: "aceitunas", nombre: "Aceitunas rellenas", unidad: "G", minimo: 500 },
  { id: "pepinillos", nombre: "Pepinillos", unidad: "G", minimo: 300 },
  { id: "mazorca", nombre: "Mazorca", unidad: "UD", minimo: 10 },
  { id: "guandules", nombre: "Guandules", unidad: "G", minimo: 800 },
  { id: "habichuelas", nombre: "Habichuelas", unidad: "G", minimo: 1000 },
  { id: "limon", nombre: "Limón", unidad: "UD", minimo: 20 },
  { id: "chinola", nombre: "Chinola", unidad: "UD", minimo: 40 },
  { id: "fresa", nombre: "Fresa", unidad: "G", minimo: 2000 },
  { id: "naranja", nombre: "Naranja", unidad: "UD", minimo: 30 },
  { id: "pina", nombre: "Piña", unidad: "UD", minimo: 10 },
  { id: "cereza", nombre: "Cereza", unidad: "G", minimo: 1000 },
  { id: "lechosa", nombre: "Lechosa", unidad: "UD", minimo: 5 },
  { id: "tamarindo", nombre: "Tamarindo", unidad: "G", minimo: 800 },
  { id: "coco", nombre: "Coco", unidad: "UD", minimo: 10 },
  { id: "arroz", nombre: "Arroz", unidad: "G", minimo: 3000 },
  { id: "pasta", nombre: "Pasta (espagueti/penne/linguini)", unidad: "G", minimo: 3000 },
  { id: "harina", nombre: "Harina de trigo", unidad: "G", minimo: 2000 },
  { id: "pan-rallado", nombre: "Pan rallado", unidad: "G", minimo: 1000 },
  { id: "baguette", nombre: "Pan baguette", unidad: "UD", minimo: 5 },
  { id: "brioche", nombre: "Pan brioche", unidad: "UD", minimo: 15 },
  { id: "crutones", nombre: "Crutones", unidad: "G", minimo: 300 },
  { id: "casabe", nombre: "Casabe", unidad: "G", minimo: 500 },
  { id: "huevo", nombre: "Huevo", unidad: "UD", minimo: 60 },
  { id: "cafe", nombre: "Café molido", unidad: "G", minimo: 2000 },
  { id: "aceite-oliva", nombre: "Aceite de oliva", unidad: "ML", minimo: 1500 },
  { id: "aceite-freir", nombre: "Aceite para freír", unidad: "ML", minimo: 5000 },
  { id: "vinagre", nombre: "Vinagre", unidad: "ML", minimo: 500 },
  { id: "ketchup", nombre: "Ketchup", unidad: "ML", minimo: 1000 },
  { id: "mayonesa", nombre: "Mayonesa", unidad: "ML", minimo: 1000 },
  { id: "mostaza", nombre: "Mostaza dijon", unidad: "G", minimo: 300 },
  { id: "salsa-bbq", nombre: "Salsa BBQ", unidad: "ML", minimo: 1000 },
  { id: "aderezo-cesar", nombre: "Aderezo césar", unidad: "ML", minimo: 800 },
  { id: "vino-tinto", nombre: "Vino tinto (cocción)", unidad: "ML", minimo: 750 },
  { id: "vino-blanco", nombre: "Vino blanco (cocción)", unidad: "ML", minimo: 750 },
  { id: "curry", nombre: "Curry", unidad: "G", minimo: 100 },
  { id: "almendras", nombre: "Almendras", unidad: "G", minimo: 300 },
  { id: "sal", nombre: "Sal", unidad: "G", minimo: 500 },
  { id: "azucar", nombre: "Azúcar", unidad: "G", minimo: 1000 },
  { id: "albahaca", nombre: "Albahaca", unidad: "G", minimo: 100 },
  { id: "cilantro", nombre: "Cilantro", unidad: "G", minimo: 200 },
  { id: "perejil", nombre: "Perejil", unidad: "G", minimo: 100 },
  { id: "oregano", nombre: "Orégano", unidad: "G", minimo: 100 },
  { id: "romero", nombre: "Romero", unidad: "G", minimo: 100 },
  { id: "finas-hierbas", nombre: "Finas hierbas", unidad: "G", minimo: 100 },
  { id: "mermelada", nombre: "Mermelada", unidad: "G", minimo: 300 },
  { id: "chocolate", nombre: "Chocolate (postre)", unidad: "G", minimo: 500 },
  { id: "maiz", nombre: "Maíz / coco rallado (majarete)", unidad: "G", minimo: 500 },
  { id: "agua-ud", nombre: "Agua (botella)", unidad: "UD", minimo: 48 },
  { id: "presidente-ud", nombre: "Presidente normal (botella)", unidad: "UD", minimo: 24 },
  { id: "salsa-alfredo-blanca", nombre: "Salsa Alfredo Blanca", unidad: "ML", minimo: 3785 },
  { id: "salsa-del-bosque", nombre: "Salsa del Bosque", unidad: "ML", minimo: 1000 },
  { id: "salsa-de-tamarindo", nombre: "Salsa de Tamarindo", unidad: "ML", minimo: 3785 },
  { id: "salsa-del-rey", nombre: "Salsa del Rey", unidad: "ML", minimo: 1000 },
  { id: "salsa-blue-cheese", nombre: "Salsa Blue Cheese", unidad: "ML", minimo: 1000 },
];

/** 1 galón US en ml — unidad de lote de las salsas base. */
export const GAL_ML = 3785.41;
const LB_G = 453.592;
const OZ_G = LB_G / 16;

export type RecipeSeed = {
  dishId: string;
  minutos?: number;
  pasos: string[];
  items: [string, number][];
};

export type PrepRecipeSeed = {
  id: string;
  nombre: string;
  outputIngredientId: string;
  rendimiento: number;
  minutos?: number;
  pasos: string[];
  items: [string, number][];
};

/** Recetas internas de lote. Solo cantidades del recetario que se pueden convertir a stock. */
export const prepRecipes: PrepRecipeSeed[] = [
  {
    id: "prep-salsa-alfredo-blanca",
    nombre: "Salsa Alfredo Blanca",
    outputIngredientId: "salsa-alfredo-blanca",
    rendimiento: 2 * GAL_ML,
    minutos: 40,
    pasos: [
      "Calentar leche y crema",
      "Integrar mantequilla",
      "Ligar con harina",
      "Reservar el lote",
    ],
    items: [
      ["leche", 2000],
      ["crema-leche", 2000],
      ["mantequilla", Math.round(0.5 * LB_G)],
      ["harina", Math.round(4 * OZ_G)],
    ],
  },
  {
    id: "prep-salsa-de-tamarindo",
    nombre: "Salsa de Tamarindo",
    outputIngredientId: "salsa-de-tamarindo",
    rendimiento: GAL_ML,
    minutos: 35,
    pasos: ["Cocer tamarindo", "Integrar mostaza y ajo", "Ligar con harina", "Reservar el lote"],
    items: [
      ["tamarindo", Math.round(LB_G)],
      ["harina", Math.round(4 * OZ_G)],
    ],
  },
];

export const recipes: RecipeSeed[] = [
  { dishId: "aros-calamar", minutos: 15, pasos: ["Sazonar anillas", "Empanar (harina-huevo-pan)", "Freír 3 min", "Servir con limón"], items: [["calamar", 200], ["harina", 50], ["huevo", 1], ["pan-rallado", 50], ["aceite-freir", 100], ["sal", 2], ["limon", 0.25]] },
  { dishId: "croquetas-pollo", minutos: 40, pasos: ["Hacer bechamel con pollo", "Enfriar y formar", "Empanar", "Freír"], items: [["pollo", 150], ["mantequilla", 20], ["harina", 40], ["leche", 150], ["huevo", 1], ["pan-rallado", 50]] },
  { dishId: "bolitas-queso", minutos: 20, pasos: ["Mezclar quesos", "Formar bolitas", "Empanar", "Freír"], items: [["mozzarella", 120], ["queso-crema", 50], ["harina", 40], ["huevo", 1], ["pan-rallado", 50]] },
  { dishId: "bruschettas", minutos: 15, pasos: ["Tostar pan", "Mezclar tomate-ajo-albahaca", "Montar y gratinar"], items: [["baguette", 1], ["tomate", 150], ["ajo", 5], ["albahaca", 5], ["aceite-oliva", 15], ["parmesano", 30]] },
  { dishId: "cativias", minutos: 25, pasos: ["Hacer masa de yuca", "Rellenar de queso", "Freír hasta dorar"], items: [["yuca", 250], ["queso-cativia", 60], ["huevo", 1], ["aceite-freir", 100]] },
  { dishId: "aceitunas-rellenas", minutos: 2, pasos: ["Servir frías"], items: [["aceitunas", 120]] },
  { dishId: "carpaccio-salmon", minutos: 10, pasos: ["Laminar fino", "Aliñar con oliva-limón", "Coronar con parmesano"], items: [["salmon", 120], ["aceite-oliva", 15], ["limon", 0.25], ["parmesano", 15], ["albahaca", 3]] },
  { dishId: "carpaccio-res", minutos: 10, pasos: ["Laminar fino", "Aliñar", "Coronar con parmesano"], items: [["filete-res", 120], ["aceite-oliva", 15], ["limon", 0.25], ["parmesano", 15], ["albahaca", 3]] },
  { dishId: "lambi-vinagreta", minutos: 30, pasos: ["Cocer lambí", "Picar", "Marinar con vegetales y vinagreta"], items: [["lambi", 200], ["cebolla", 40], ["pimiento", 30], ["vinagre", 20], ["aceite-oliva", 15], ["cilantro", 5]] },
  { dishId: "coctel-camarones", minutos: 20, pasos: ["Cocer camarones", "Preparar salsa rosada", "Servir en copa con aguacate"], items: [["camarones", 150], ["ketchup", 50], ["mayonesa", 30], ["limon", 0.25], ["aguacate", 0.25], ["lechuga", 20]] },
  { dishId: "tabla-quesos", minutos: 10, pasos: ["Montar tabla fría"], items: [["manchego", 60], ["iberico", 60], ["queso-cabra", 60], ["jamon-serrano", 50], ["aceitunas", 40], ["baguette", 1], ["mermelada", 40]] },
  { dishId: "chivo-del-valle", minutos: 90, pasos: ["Lavar con limón y sazonar", "Cocer hasta ablandar", "Terminar en salsa de la casa"], items: [["chivo", 350], ["cebolla", 60], ["ajo", 10], ["oregano", 3], ["limon", 0.5], ["tomate", 80], ["vino-tinto", 50]] },
  { dishId: "conejo", minutos: 50, pasos: ["Sazonar", "Cocer", "Terminar a la parrilla con romero"], items: [["conejo", 350], ["romero", 5], ["ajo", 10], ["aceite-oliva", 20], ["sal", 3]] },
  { dishId: "gallina-criolla", minutos: 80, pasos: ["Cocer", "Terminar en salsa de la casa"], items: [["gallina", 350], ["cebolla", 60], ["ajo", 10], ["oregano", 3], ["limon", 0.5], ["tomate", 80], ["vino-tinto", 50]] },
  { dishId: "pechuga-parrilla", minutos: 20, pasos: ["Sazonar", "Grillar al término solicitado"], items: [["pechuga", 250], ["ajo", 5], ["sal", 3], ["aceite-oliva", 10]] },
  { dishId: "pechuga-salsa-rey", minutos: 25, pasos: ["Grillar pechuga", "Napar con salsa del rey"], items: [["pechuga", 250], ["champinones", 50], ["cebolla", 30], ["crema-leche", 80], ["vino-blanco", 30]] },
  { dishId: "filete-cerdo-parrilla", minutos: 20, pasos: ["Sazonar y grillar"], items: [["filete-cerdo", 250], ["ajo", 5], ["sal", 3]] },
  { dishId: "filete-cerdo-mostaza", minutos: 25, pasos: ["Grillar", "Napar con salsa de mostaza"], items: [["filete-cerdo", 250], ["mostaza", 20], ["crema-leche", 80], ["finas-hierbas", 3]] },
  { dishId: "costillas-bbq", minutos: 90, pasos: ["Cocer costillas", "Bañar en BBQ", "Terminar al grill"], items: [["costilla-cerdo", 350], ["salsa-bbq", 80], ["ajo", 5]] },
  { dishId: "bistec-encebollado", minutos: 25, pasos: ["Sellar bistec", "Saltear cebolla", "Deglasear con vino tinto"], items: [["bistec-res", 250], ["cebolla", 100], ["vino-tinto", 50], ["ajo", 5]] },
  { dishId: "filete-res-parrilla", minutos: 20, pasos: ["Grillar al término", "Terminar con mantequilla"], items: [["filete-res", 250], ["sal", 3], ["mantequilla", 10]] },
  { dishId: "filete-res-queso-azul", minutos: 25, pasos: ["Grillar", "Napar con salsa de queso azul"], items: [["filete-res", 250], ["queso-azul", 40], ["crema-leche", 80]] },
  { dishId: "churrasco-angus", minutos: 20, pasos: ["Grillar al término"], items: [["churrasco", 225], ["sal", 3], ["mantequilla", 10]] },
  { dishId: "flap-meat", minutos: 20, pasos: ["Grillar al término"], items: [["flap-meat", 225], ["sal", 3], ["mantequilla", 10]] },
  { dishId: "ribeye", minutos: 20, pasos: ["Grillar", "Terminar con salsa de finas hierbas"], items: [["ribeye", 225], ["finas-hierbas", 5], ["mantequilla", 15], ["sal", 3]] },
  { dishId: "ensalada-constancera", minutos: 8, pasos: ["Montar fresca", "Aderezo al gusto"], items: [["lechuga", 80], ["tomate", 80], ["pepino", 60], ["zanahoria", 40]] },
  { dishId: "ensalada-cesar", minutos: 15, pasos: ["Grillar pollo", "Montar sobre lechuga", "Aderezar"], items: [["lechuga", 100], ["pechuga", 120], ["parmesano", 20], ["crutones", 30], ["aderezo-cesar", 40]] },
  { dishId: "ensalada-capressa", minutos: 8, pasos: ["Alternar láminas", "Albahaca y oliva"], items: [["tomate", 120], ["mozzarella", 100], ["albahaca", 5], ["aceite-oliva", 15]] },
  { dishId: "ensalada-mar", minutos: 20, pasos: ["Cocer mariscos", "Montar fría"], items: [["mix-mariscos", 200], ["lechuga", 60], ["tomate", 50], ["aceite-oliva", 15], ["limon", 0.25]] },
  { dishId: "sancocho", minutos: 75, pasos: ["Cocer carnes", "Agregar tubérculos por dureza", "Servir con arroz"], items: [["bistec-res", 120], ["filete-cerdo", 100], ["pollo", 100], ["yuca", 80], ["name", 60], ["platano-verde", 0.5], ["auyama", 60], ["mazorca", 0.5], ["cilantro", 10], ["arroz", 120]] },
  { dishId: "caldo-pollo", minutos: 40, pasos: ["Cocer todo junto hasta punto"], items: [["pollo", 200], ["papa", 80], ["zanahoria", 50], ["apio", 30], ["auyama", 60], ["cilantro", 10]] },
  { dishId: "caldo-mar", minutos: 35, pasos: ["Fumé base", "Agregar mariscos al final"], items: [["mix-mariscos", 200], ["salmon", 80], ["apio", 30], ["zanahoria", 40], ["cilantro", 10]] },
  { dishId: "bastoncitos-pollo", minutos: 20, pasos: ["Empanar tiras", "Freír"], items: [["pechuga", 200], ["harina", 50], ["huevo", 1], ["pan-rallado", 50]] },
  { dishId: "canastitas-pollo", minutos: 25, pasos: ["Formar canasta de plátano", "Freír", "Rellenar"], items: [["platano-verde", 1], ["pechuga", 150], ["cebolla", 30], ["crema-leche", 60]] },
  { dishId: "canastitas-camarones", minutos: 25, pasos: ["Canasta frita", "Rellenar de camarones"], items: [["platano-verde", 1], ["camarones", 150], ["ajo", 10]] },
  { dishId: "carne-salada", minutos: 30, pasos: ["Desalar", "Guisar con vegetales"], items: [["carne-salada", 250], ["cebolla", 50], ["pimiento", 40], ["tomate", 50]] },
  { dishId: "salchicha-parrillera", minutos: 12, pasos: ["Grillar"], items: [["salchicha", 200]] },
  { dishId: "hamburguesa-especial", minutos: 20, pasos: ["Grillar carne", "Montar con toppings", "Servir con papas"], items: [["carne-molida", 180], ["brioche", 1], ["gouda", 30], ["tocineta", 30], ["tomate", 30], ["lechuga", 20], ["cebolla", 20], ["pepinillos", 15], ["papa", 150]] },
  { dishId: "hamburguesa-pollo", minutos: 20, pasos: ["Grillar pechuga", "Montar", "Servir con papas"], items: [["pechuga", 180], ["brioche", 1], ["gouda", 30], ["tomate", 30], ["lechuga", 20], ["cebolla", 20], ["pepinillos", 15], ["papa", 150]] },
  { dishId: "tabla-mixta", minutos: 30, pasos: ["Grillar todo", "Montar tabla"], items: [["filete-cerdo", 250], ["pechuga", 250], ["filete-res", 250], ["salchicha", 200]] },
  { dishId: "pasta-alfredo-pollo", minutos: 25, pasos: ["Cocer pasta", "Salsa alfredo", "Integrar pollo grillado"], items: [["pasta", 120], ["pechuga", 150], ["crema-leche", 100], ["mantequilla", 20], ["parmesano", 30], ["ajo", 5]] },
  { dishId: "pasta-alfredo-camarones", minutos: 25, pasos: ["Cocer pasta", "Salsa alfredo", "Camarones salteados"], items: [["pasta", 120], ["camarones", 150], ["crema-leche", 100], ["mantequilla", 20], ["parmesano", 30], ["ajo", 5]] },
  { dishId: "pasta-tomate", minutos: 20, pasos: ["Salsa fresca de tomate", "Terminar con albahaca"], items: [["pasta", 120], ["tomate", 150], ["parmesano", 30], ["albahaca", 5], ["aceite-oliva", 20]] },
  { dishId: "pasta-tomate-camarones", minutos: 25, pasos: ["Salsa de tomate", "Camarones"], items: [["pasta", 120], ["tomate", 150], ["camarones", 150], ["parmesano", 30], ["albahaca", 5], ["aceite-oliva", 20]] },
  { dishId: "pasta-4-quesos", minutos: 20, pasos: ["Fundir quesos en crema", "Integrar pasta"], items: [["pasta", 120], ["mozzarella", 30], ["parmesano", 20], ["gouda", 30], ["queso-azul", 20], ["crema-leche", 80]] },
  { dishId: "pasta-tocineta", minutos: 20, pasos: ["Dorar tocineta", "Salsa cremosa", "Integrar"], items: [["pasta", 120], ["tocineta", 60], ["parmesano", 30], ["crema-leche", 80]] },
  { dishId: "pasta-marinera", minutos: 30, pasos: ["Saltar mariscos", "Salsa de tomate fresco", "Integrar pasta"], items: [["pasta", 120], ["camarones", 60], ["salmon", 50], ["calamar", 50], ["mejillones", 50], ["tomate", 150], ["ajo", 5]] },
  { dishId: "arroz-mariscos", minutos: 35, pasos: ["Sofrito base", "Cocer arroz con mariscos"], items: [["arroz", 150], ["mix-mariscos", 200], ["cebolla", 30], ["pimiento", 20]] },
  { dishId: "asopao-camarones", minutos: 30, pasos: ["Sofrito", "Arroz caldoso con camarones"], items: [["arroz", 120], ["camarones", 180], ["tomate", 60], ["cebolla", 30], ["cilantro", 5]] },
  { dishId: "asopao-mariscos", minutos: 30, pasos: ["Sofrito", "Arroz caldoso con mix"], items: [["arroz", 120], ["mix-mariscos", 200], ["tomate", 60], ["cebolla", 30], ["cilantro", 5]] },
  { dishId: "salmon-parrilla", minutos: 18, pasos: ["Grillar", "Terminar con mantequilla y limón"], items: [["salmon", 220], ["sal", 2], ["mantequilla", 10], ["limon", 0.25]] },
  { dishId: "salmon-bosque", minutos: 22, pasos: ["Grillar", "Napar con salsa del bosque"], items: [["salmon", 220], ["champinones", 60], ["crema-leche", 80], ["finas-hierbas", 3]] },
  { dishId: "camarones-almendras", minutos: 18, pasos: ["Rostizar camarones", "Salsa de almendras"], items: [["camarones", 200], ["almendras", 30], ["crema-leche", 80]] },
  { dishId: "camarones-ajillo", minutos: 12, pasos: ["Saltear en oliva con ajo", "Terminar con perejil"], items: [["camarones", 200], ["ajo", 15], ["aceite-oliva", 30], ["perejil", 5]] },
  { dishId: "camarones-crema", minutos: 15, pasos: ["Saltear", "Terminar en crema"], items: [["camarones", 200], ["crema-leche", 100], ["parmesano", 15]] },
  { dishId: "lambi-plato", minutos: 30, pasos: ["Cocer lambí", "Servir en vinagreta o criolla"], items: [["lambi", 250], ["cebolla", 40], ["pimiento", 30], ["tomate", 60]] },
  { dishId: "lambi-criolla", minutos: 30, pasos: ["Cocer lambí", "Guisar a la criolla"], items: [["lambi", 250], ["cebolla", 40], ["pimiento", 30], ["tomate", 60]] },
  { dishId: "langostinos-bandera", minutos: 20, pasos: ["Preparar al estilo elegido"], items: [["langostinos", 250], ["crema-leche", 100], ["curry", 5], ["mantequilla", 15]] },
  { dishId: "tostones", minutos: 10, pasos: ["Freír, aplastar, volver a freír"], items: [["platano-verde", 1]] },
  { dishId: "casabe", minutos: 5, pasos: ["Tostar"], items: [["casabe", 60]] },
  { dishId: "papas-fritas", minutos: 12, pasos: ["Cortar y freír"], items: [["papa", 150]] },
  { dishId: "papas-salteadas", minutos: 12, pasos: ["Saltear"], items: [["papa", 150]] },
  { dishId: "aguacate", minutos: 2, pasos: ["Cortar y servir"], items: [["aguacate", 0.5]] },
  { dishId: "vegetales-grill", minutos: 12, pasos: ["Grillar mix de vegetales"], items: [["tomate", 50], ["pimiento", 50], ["cebolla", 50]] },
  { dishId: "yuca-frita", minutos: 15, pasos: ["Cocer y freír"], items: [["yuca", 150]] },
  { dishId: "tostones-maduro", minutos: 10, pasos: ["Freír maduro"], items: [["platano-maduro", 1]] },
  { dishId: "pure-papa", minutos: 20, pasos: ["Cocer y triturar"], items: [["papa", 150], ["mantequilla", 15], ["leche", 40]] },
  { dishId: "chips-yautia", minutos: 12, pasos: ["Laminar y freír"], items: [["yautia", 100]] },
  { dishId: "pure-cepa", minutos: 20, pasos: ["Cocer y triturar"], items: [["cepa-apio", 150], ["crema-leche", 30]] },
  { dishId: "moro-guandules", minutos: 30, pasos: ["Sofrito", "Cocer arroz con guandules"], items: [["arroz", 100], ["guandules", 50]] },
  { dishId: "arroz-blanco", minutos: 18, pasos: ["Cocer arroz"], items: [["arroz", 120]] },
  { dishId: "habichuelas", minutos: 40, pasos: ["Guisar habichuelas"], items: [["habichuelas", 100]] },
  { dishId: "guandules-guisados", minutos: 40, pasos: ["Guisar guandules"], items: [["guandules", 100]] },
  { dishId: "tostones-cepa", minutos: 12, pasos: ["Cortar, freír y aplastar"], items: [["cepa-apio", 150]] },
  { dishId: "quesillo-coco", minutos: 50, pasos: ["Mezclar", "Hornear a baño maría", "Enfriar"], items: [["huevo", 2], ["leche", 150], ["azucar", 40], ["coco", 0.3]] },
  { dishId: "majarete", minutos: 40, pasos: ["Cocer maíz/coco con leche", "Endulzar"], items: [["maiz", 80], ["leche", 150], ["azucar", 40]] },
  { dishId: "dulce-coco", minutos: 30, pasos: ["Cocer coco con azúcar"], items: [["coco", 1], ["azucar", 50]] },
  { dishId: "bizcocho-chocolate", minutos: 45, pasos: ["Batir", "Hornear"], items: [["harina", 60], ["chocolate", 50], ["huevo", 1], ["mantequilla", 30], ["azucar", 40]] },
  { dishId: "helado", minutos: 2, pasos: ["Servir"], items: [["helado-vainilla", 150]] },
];

/** Unidades vendidas 1 jun – 31 jul 2026 (reporte POS). */
export const historicalUnits: Record<string, number> = {
  agua: 277, "cafe-negro": 219, "chivo-del-valle": 141, presidente: 139, "jugo-chinola": 120,
  aguacate: 101, "jugo-limon": 100, habichuelas: 96, cativias: 87, "pechuga-parrilla": 82,
  sancocho: 82, "croquetas-pollo": 80, "almuerzo-ejecutivo": 76, "corona-extra": 75,
  "quesillo-coco": 63, "costillas-bbq": 60, "tostones": 61, "cafe-crema": 61, "presidente-light": 60,
  "jugo-fresa": 69, "bistec-encebollado": 53, "hamburguesa-especial": 51, "frozen-fresa": 51,
  "coca-cola": 73, "sangria-roja": 47, "cafe-leche": 47, perrier: 46, "coca-zero": 44,
  "club-soda": 43, "bolitas-queso": 42, "filete-cerdo-parrilla": 43, "modelo-especial": 40,
  "pasta-alfredo-pollo": 40, "bastoncitos-pollo": 39, conejo: 39, "frozen-limon-menta": 37,
  tamarindo: 37, "gallina-criolla": 36, "pasta-alfredo-camarones": 36, "jugo-cereza": 36,
  "pechuga-salsa-rey": 35, majarete: 35, "aperol-spritz": 35, "filete-res-parrilla": 34,
  "salmon-parrilla": 34, "agua-llevar": 34, cortadito: 33, "churrasco-angus": 32,
  "pina-colada-sin": 32, "zumo-limon": 32, "jugo-pina": 31, "ensalada-constancera": 30,
  "frozen-chinola": 30, "desayuno-dominicano": 29, stella: 28, "morir-chinola": 28,
  "aros-calamar": 27, "pina-colada": 26, expresso: 25, "bruschettas": 25, "san-pellegrino-1l": 25,
  "pasta-4-quesos": 24, helado: 24, "brisa-del-valle": 23, "bizcocho-chocolate": 22,
  sprite: 21, "camarones-ajillo": 21, "morir-naranja": 21, "jugo-naranja": 21,
  "filete-res-queso-azul": 20, bohemia: 20, "papas-fritas": 20, "fresa-leche": 18,
  "frozen-limon": 18, "carne-salada": 17, "filete-cerdo-mostaza": 17, "pasta-tomate": 17,
  "pasta-tocineta": 16, "hamburguesa-pollo": 15, "tabla-mixta": 15, heineken: 15,
  "chocolate-leche": 15, "ensalada-cesar": 14, "canastitas-pollo": 14, "micky-mouse": 14,
  "mojito-coco": 14, "smirnoff-green": 14, "arroz-blanco": 13, "salmon-bosque": 13,
  "mojito-chinola": 13, "carpaccio-res": 12, "salchicha-parrillera": 12, "te-jengibre": 12,
  "desayuno-americano": 11, omelette: 11, "caldo-pollo": 11, "pasta-tomate-camarones": 11,
  "pan-tostado": 11, "asopao-camarones": 11, "camarones-crema": 11, "canastitas-camarones": 11,
  "modelo-negra": 11, negroni: 11, "expresso-martini": 11, cointreau: 11,
  "carpaccio-salmon": 10, "gin-tonic-bombay": 10, "coctel-camarones": 9, "flap-meat": 9,
  ribeye: 9, "tostones-maduro": 9, "corona-zero": 9, "paulaner-dunkel": 9, caipirinha: 9,
  "margarita-fresa": 9, "lambi-vinagreta": 8, "lambi-plato": 8, "pure-cepa": 8,
  "ocean-blue": 8, frappe: 8, "copa-blanco": 8, "margarita-clasica": 8, "morir-limon": 8,
  "caldo-mar": 7, "arroz-mariscos": 7, "pechuga-crema": 7, "vegetales-grill": 7,
  "yuca-frita": 7, "ginger-ale": 7, "paulaner-grande": 7, "mojito-limon": 7,
  "tostada-rustica": 6, "san-pellegrino-250": 6, "lechosa-leche": 6, "gin-tonic-especiado": 6,
  "mojito-fresa": 6, "barcelo-blanco": 6, "el-ligero": 5, casabe: 5, clamato: 5,
  "jugo-limon-menta": 5, "erdinger-dunkel": 5, miller: 5, "gin-tonic-afrutado": 5,
  "sangria-blanca": 5, "tabla-quesos": 4, "chips-yautia": 4, "sandwich-jamon-queso": 4,
  "derretido-queso": 4, "huevos-estrellados": 4, "extra-huevo": 4, "bizcocho-moda": 4,
  "cafe-leche-almendra": 4, tonica: 4, "blue-moon": 4, "paulaner-pequena": 4,
  "smirnoff-ice": 4, "six-eight-nine": 4, "margarita-chinola": 4, mimosa: 4,
  "sangria-rosada": 4, tentacion: 4, "tequila-sunrise": 4, fernet: 4, "glenlivet-12": 4,
  "aceitunas-extra": 4, "emp-hamburguesa": 4,
  "ensalada-capressa": 3, "extra-parmesano": 3, "leche-extra": 3, "red-bull": 3,
  "segura-viudas": 3, "gin-rosado-beefeater": 3, "gin-tonic-beefeater": 3,
  disaronno: 3, "jw-double-black": 3, limoncello: 3, "doble-reserva": 3, "emp-sancocho": 3,
  "emp-flan": 3, croissant: 2, "bizcocho-sorpresa": 2, "quesillo-sorpresa": 2,
  "pure-papa": 2, "tostones-cepa": 2, "expresso-doble": 2, "te-frio": 2,
  "heineken-grande": 2, "jugo-lechosa": 2, "frozen-fresa-limon": 2, "bogle-cab": 2,
  "pra-chardonnay": 2, "protos-verdejo": 2, "cuba-libre": 2, "long-island": 2,
  dewars: 2, "jw-black": 2, "don-julio": 2, "grey-goose": 2, "tia-maria": 2,
  b52: 2, "extra-tocineta": 2, "extra-mozzarella": 2, "salsa-crema": 2,
  "emp-presidente": 2, "emp-sprite": 2, "hue-dominicano": 2, "hue-sandwich": 2,
  "hue-cafe": 2, "emp-soda-amarga": 10,
  "ensalada-mar": 1, "pasta-marinera": 1, "pasta-crema-blanca": 1, "lambi-criolla": 1,
  "camarones-criolla": 1, "croissant-jamon": 1, "guandules-guisados": 1, "moro-guandules": 1,
  "papas-salteadas": 1, "extra-pollo": 1, "extra-salami": 1, "vaso-plastico": 1,
  "emp-bistec": 1, "emp-caldo-pollo": 1, "emp-croquetas": 1, "emp-filete": 1,
  "emp-pechuga": 1, "emp-salchicha": 1, "chocolate-agua": 1, "taza-leche": 1,
  "chinola-fresa-frozen": 1, "jugo-melon": 1, "jugo-fresa-limon": 1, "mezcla-frutas": 1,
  "paulaner-sin": 1, "erdinger-rubia": 1, "heineken-cero": 1, "ilauri-prosecco": 1,
  "bloody-mary": 1, "john-collins": 1, "margarita-deluxe": 1, "vodka-sol": 1,
  "old-parr": 1, "fernet-menta": 1, bombay: 1, ginebra: 1, "brugal-1888": 1,
  descorche: 1, "descorche-chivas": 1, "extra-leche-almendra": 1, "vaso-hielo": 1,
  "vela-cumple": 1, "hue-agua": 1, "hue-chinola": 1, "hue-limon": 1,
  "emp-agua": 71, "emp-coca": 36,
};
